#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

account.cart.add

.DESCRIPTION

No description available.

.PARAMETER AccountCartAdd
No description available.

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccountCartAdd200Response
#>
function Invoke-AccountCartAdd {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [PSCustomObject]
        ${AccountCartAdd},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccountCartAdd' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        # HTTP header 'Content-Type'
        $LocalVarContentTypes = @('application/json')

        $LocalVarUri = '/account.cart.add.json'

        if (!$AccountCartAdd) {
            throw "Error! The required parameter `AccountCartAdd` missing when calling accountCartAdd."
        }

        $LocalVarBodyParameter = $AccountCartAdd | ConvertTo-Json -Depth 100

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'POST' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccountCartAdd200Response" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

account.cart.list

.DESCRIPTION

No description available.

.PARAMETER StoreUrl
A web address of a store

.PARAMETER StoreKey
Find store by store key

.PARAMETER RequestFromDate
Retrieve entities from their creation date

.PARAMETER RequestToDate
Retrieve entities to their creation date

.PARAMETER Params
Set this parameter in order to choose which entity fields you want to retrieve

.PARAMETER Exclude
Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccountCartList200Response
#>
function Invoke-AccountCartList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${StoreUrl},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${StoreKey},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RequestFromDate},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RequestToDate},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Params},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Exclude},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccountCartList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/account.cart.list.json'

        if ($StoreUrl) {
            $LocalVarQueryParameters['store_url'] = $StoreUrl
        }

        if ($StoreKey) {
            $LocalVarQueryParameters['store_key'] = $StoreKey
        }

        if ($RequestFromDate) {
            $LocalVarQueryParameters['request_from_date'] = $RequestFromDate
        }

        if ($RequestToDate) {
            $LocalVarQueryParameters['request_to_date'] = $RequestToDate
        }

        if ($Params) {
            $LocalVarQueryParameters['params'] = $Params
        }

        if ($Exclude) {
            $LocalVarQueryParameters['exclude'] = $Exclude
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccountCartList200Response" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

account.config.update

.DESCRIPTION

No description available.

.PARAMETER ReplaceParameters
Identifies if there is a necessity to replace parameters

.PARAMETER NewStoreUrl
The web address of the store you want to update to connect to API2Cart

.PARAMETER NewStoreKey
Update store key

.PARAMETER BridgeUrl
This parameter allows to set up store with custom bridge url (also you must use store_root parameter if a bridge folder is not in the root folder of the store)

.PARAMETER StoreRoot
Absolute path to the store root directory (used with ""bridge_url"" parameter)

.PARAMETER DbTablesPrefix
DB tables prefix

.PARAMETER UserAgent
This parameter allows you to set your custom user agent, which will be used in requests to the store. Please use it cautiously, as the store's firewall may block specific values.

.PARAMETER Var3dcartPrivateKey
3DCart Private Key

.PARAMETER Var3dcartAccessToken
3DCart Token

.PARAMETER Var3dcartapiApiKey
3DCart API Key

.PARAMETER AmazonSpClientId
Amazon SP API app client id

.PARAMETER AmazonSpClientSecret
Amazon SP API app client secret

.PARAMETER AmazonSpRefreshToken
Amazon SP API OAuth refresh token

.PARAMETER AmazonSpAwsRegion
Amazon AWS Region

.PARAMETER AmazonSpApiEnvironment
Amazon SP API environment

.PARAMETER AmazonSellerId
Amazon Seller ID (Merchant token)

.PARAMETER AspdotnetstorefrontApiUser
It's a AspDotNetStorefront account for which API is available

.PARAMETER AspdotnetstorefrontApiPass
AspDotNetStorefront API Password

.PARAMETER BigcommerceapiAdminAccount
It's a BigCommerce account for which API is enabled

.PARAMETER BigcommerceapiApiPath
BigCommerce API URL

.PARAMETER BigcommerceapiApiKey
Bigcommerce API Key

.PARAMETER BigcommerceapiClientId
Client ID of the requesting app

.PARAMETER BigcommerceapiAccessToken
Access token authorizing the app to access resources on behalf of a user

.PARAMETER BigcommerceapiContext
API Path section unique to the store

.PARAMETER BolApiKey
Bol API Key

.PARAMETER BolApiSecret
Bol API Secret

.PARAMETER BolRetailerId
Bol Retailer ID

.PARAMETER DemandwareClientId
Demandware client id

.PARAMETER DemandwareApiPassword
Demandware api password

.PARAMETER DemandwareUserName
Demandware user name

.PARAMETER DemandwareUserPassword
Demandware user password

.PARAMETER EbayClientId
Application ID (AppID).

.PARAMETER EbayClientSecret
Shared Secret from eBay application

.PARAMETER EbayRuname
The RuName value that eBay assigns to your application.

.PARAMETER EbayAccessToken
Used to authenticate API requests.

.PARAMETER EbayRefreshToken
Used to renew the access token.

.PARAMETER EbayEnvironment
eBay environment

.PARAMETER EbaySiteId
eBay global ID

.PARAMETER EcwidAcessToken
Access token authorizing the app to access resources on behalf of a user

.PARAMETER EcwidStoreId
Store Id

.PARAMETER LazadaAppId
Lazada App ID

.PARAMETER LazadaAppSecret
Lazada App Secret

.PARAMETER LazadaRefreshToken
Lazada Refresh Token

.PARAMETER LazadaRegion
Lazada API endpoint Region

.PARAMETER EtsyKeystring
Etsy keystring

.PARAMETER EtsySharedSecret
Etsy shared secret

.PARAMETER EtsyAccessToken
Access token authorizing the app to access resources on behalf of a user

.PARAMETER EtsyTokenSecret
Secret token authorizing the app to access resources on behalf of a user

.PARAMETER EtsyClientId
Etsy Client Id

.PARAMETER EtsyRefreshToken
Etsy Refresh token

.PARAMETER FacebookAppId
Facebook App ID

.PARAMETER FacebookAppSecret
Facebook App Secret

.PARAMETER FacebookAccessToken
Facebook Access Token

.PARAMETER FacebookBusinessId
Facebook Business ID

.PARAMETER NetoApiKey
Neto API Key

.PARAMETER NetoApiUsername
Neto User Name

.PARAMETER ShoplineAccessToken
Shopline APP Key

.PARAMETER ShoplineAppKey
Shopline APP Key

.PARAMETER ShoplineAppSecret
Shopline App Secret

.PARAMETER ShoplineSharedSecret
Shopline Shared Secret

.PARAMETER ShopifyAccessToken
Access token authorizing the app to access resources on behalf of a user

.PARAMETER ShopifyApiKey
Shopify API Key

.PARAMETER ShopifyApiPassword
Shopify API Password

.PARAMETER ShopifySharedSecret
Shared secret

.PARAMETER ShopeePartnerId
Shopee Partner ID

.PARAMETER ShopeePartnerKey
Shopee Partner Key

.PARAMETER ShopeeShopId
Shopee SHOP ID

.PARAMETER ShopeeRefreshToken
Shopee Refresh Token

.PARAMETER ShopeeRegion
Shopee API endpoint Region. Use for Chinese Mainland or Brazil.

.PARAMETER ShopeeEnvironment
Shopee Environment

.PARAMETER ShoplazzaAccessToken
Access token authorizing the app to access resources on behalf of a user

.PARAMETER ShoplazzaSharedSecret
Shared secret

.PARAMETER MivaAccessToken
Miva access token

.PARAMETER MivaSignature
Miva signature

.PARAMETER ShopwareAccessKey
Shopware access key

.PARAMETER UnasApiKey
UNAS API Key

.PARAMETER ShopwareApiKey
Shopware api key

.PARAMETER ShopwareApiSecret
Shopware client secret access key

.PARAMETER BigcartelUserName
Subdomain of store

.PARAMETER BigcartelPassword
BigCartel account password

.PARAMETER BricklinkConsumerKey
Bricklink Consumer Key

.PARAMETER BricklinkConsumerSecret
Bricklink Consumer Secret

.PARAMETER BricklinkToken
Bricklink Access Token

.PARAMETER BricklinkTokenSecret
Bricklink Access Token Secret

.PARAMETER VolusionLogin
It's a Volusion account for which API is enabled

.PARAMETER VolusionPassword
Volusion API Password

.PARAMETER WalmartClientId
Walmart client ID. For the region 'ca' use Consumer ID

.PARAMETER WalmartClientSecret
Walmart client secret. For the region 'ca' use Private Key

.PARAMETER WalmartEnvironment
Walmart environment

.PARAMETER WalmartChannelType
Walmart WM_CONSUMER.CHANNEL.TYPE header

.PARAMETER WalmartRegion
Walmart region

.PARAMETER SquareClientId
Square (Weebly) Client ID

.PARAMETER SquareClientSecret
Square (Weebly) Client Secret

.PARAMETER SquareRefreshToken
Square (Weebly) Refresh Token

.PARAMETER SquarespaceApiKey
Squarespace API Key

.PARAMETER SquarespaceClientId
Squarespace Connector Client ID

.PARAMETER SquarespaceClientSecret
Squarespace Connector Client Secret

.PARAMETER SquarespaceAccessToken
Squarespace access token

.PARAMETER SquarespaceRefreshToken
Squarespace refresh token

.PARAMETER HybrisClientId
Omni Commerce Connector Client ID

.PARAMETER HybrisClientSecret
Omni Commerce Connector Client Secret

.PARAMETER HybrisUsername
User Name

.PARAMETER HybrisPassword
User password

.PARAMETER HybrisWebsites
Websites to stores mapping data

.PARAMETER LightspeedApiKey
LightSpeed api key

.PARAMETER LightspeedApiSecret
LightSpeed api secret

.PARAMETER CommercehqApiKey
CommerceHQ api key

.PARAMETER CommercehqApiPassword
CommerceHQ api password

.PARAMETER WcConsumerKey
Woocommerce consumer key

.PARAMETER WcConsumerSecret
Woocommerce consumer secret

.PARAMETER MagentoConsumerKey
Magento Consumer Key

.PARAMETER MagentoConsumerSecret
Magento Consumer Secret

.PARAMETER MagentoAccessToken
Magento Access Token

.PARAMETER MagentoTokenSecret
Magento Token Secret

.PARAMETER PrestashopWebserviceKey
Prestashop webservice key

.PARAMETER WixAppId
Wix App ID

.PARAMETER WixAppSecretKey
Wix App Secret Key

.PARAMETER WixInstanceId
Wix Instance ID

.PARAMETER WixRefreshToken
Wix refresh token

.PARAMETER MercadoLibreAppId
Mercado Libre App ID

.PARAMETER MercadoLibreAppSecretKey
Mercado Libre App Secret Key

.PARAMETER MercadoLibreRefreshToken
Mercado Libre Refresh Token

.PARAMETER ZidClientId
Zid Client ID

.PARAMETER ZidClientSecret
Zid Client Secret

.PARAMETER ZidAccessToken
Zid Access Token

.PARAMETER ZidAuthorization
Zid Authorization

.PARAMETER ZidRefreshToken
Zid refresh token

.PARAMETER FlipkartClientId
Flipkart Client ID

.PARAMETER FlipkartClientSecret
Flipkart Client Secret

.PARAMETER AllegroClientId
Allegro Client ID

.PARAMETER AllegroClientSecret
Allegro Client Secret

.PARAMETER AllegroAccessToken
Allegro Access Token

.PARAMETER AllegroRefreshToken
Allegro Refresh Token

.PARAMETER AllegroEnvironment
Allegro Environment

.PARAMETER ZohoClientId
Zoho Client ID

.PARAMETER ZohoClientSecret
Zoho Client Secret

.PARAMETER ZohoRefreshToken
Zoho Refresh Token

.PARAMETER ZohoRegion
Zoho API endpoint Region

.PARAMETER TiendanubeUserId
Tiendanube User ID

.PARAMETER TiendanubeAccessToken
Tiendanube Access Token

.PARAMETER TiendanubeClientSecret
Tiendanube Client Secret

.PARAMETER OttoClientId
Otto Client ID

.PARAMETER OttoClientSecret
Otto Client Secret

.PARAMETER OttoAppId
Otto App ID

.PARAMETER OttoRefreshToken
Otto Refresh Token

.PARAMETER OttoEnvironment
Otto Environment

.PARAMETER OttoAccessToken
Otto Access Token

.PARAMETER TiktokshopAppKey
TikTok Shop App Key

.PARAMETER TiktokshopAppSecret
TikTok Shop App Secret

.PARAMETER TiktokshopRefreshToken
TikTok Shop Refresh Token

.PARAMETER TiktokshopAccessToken
TikTok Shop Access Token

.PARAMETER SallaClientId
Salla Client ID

.PARAMETER SallaClientSecret
Salla Client Secret

.PARAMETER SallaRefreshToken
Salla Refresh Token

.PARAMETER SallaAccessToken
Salla Access Token

.PARAMETER TemuAppKey
Temu App Key

.PARAMETER TemuAppSecret
Temu App Secret

.PARAMETER TemuAccessToken
Temu Access Token

.PARAMETER TemuRegion
Temu API endpoint Region.

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccountConfigUpdate200Response
#>
function Invoke-AccountConfigUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Boolean]]
        ${ReplaceParameters},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${NewStoreUrl},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${NewStoreKey},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BridgeUrl},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${StoreRoot},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${DbTablesPrefix},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${UserAgent},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Var3dcartPrivateKey},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Var3dcartAccessToken},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Var3dcartapiApiKey},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSpClientId},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSpClientSecret},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSpRefreshToken},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSpAwsRegion},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSpApiEnvironment},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AmazonSellerId},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AspdotnetstorefrontApiUser},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AspdotnetstorefrontApiPass},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiAdminAccount},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiApiPath},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiApiKey},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiClientId},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiAccessToken},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcommerceapiContext},
        [Parameter(Position = 24, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BolApiKey},
        [Parameter(Position = 25, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BolApiSecret},
        [Parameter(Position = 26, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${BolRetailerId},
        [Parameter(Position = 27, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${DemandwareClientId},
        [Parameter(Position = 28, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${DemandwareApiPassword},
        [Parameter(Position = 29, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${DemandwareUserName},
        [Parameter(Position = 30, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${DemandwareUserPassword},
        [Parameter(Position = 31, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayClientId},
        [Parameter(Position = 32, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayClientSecret},
        [Parameter(Position = 33, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayRuname},
        [Parameter(Position = 34, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayAccessToken},
        [Parameter(Position = 35, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayRefreshToken},
        [Parameter(Position = 36, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EbayEnvironment},
        [Parameter(Position = 37, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${EbaySiteId},
        [Parameter(Position = 38, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EcwidAcessToken},
        [Parameter(Position = 39, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EcwidStoreId},
        [Parameter(Position = 40, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LazadaAppId},
        [Parameter(Position = 41, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LazadaAppSecret},
        [Parameter(Position = 42, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LazadaRefreshToken},
        [Parameter(Position = 43, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LazadaRegion},
        [Parameter(Position = 44, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsyKeystring},
        [Parameter(Position = 45, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsySharedSecret},
        [Parameter(Position = 46, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsyAccessToken},
        [Parameter(Position = 47, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsyTokenSecret},
        [Parameter(Position = 48, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsyClientId},
        [Parameter(Position = 49, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${EtsyRefreshToken},
        [Parameter(Position = 50, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FacebookAppId},
        [Parameter(Position = 51, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FacebookAppSecret},
        [Parameter(Position = 52, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FacebookAccessToken},
        [Parameter(Position = 53, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FacebookBusinessId},
        [Parameter(Position = 54, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${NetoApiKey},
        [Parameter(Position = 55, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${NetoApiUsername},
        [Parameter(Position = 56, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplineAccessToken},
        [Parameter(Position = 57, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplineAppKey},
        [Parameter(Position = 58, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplineAppSecret},
        [Parameter(Position = 59, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplineSharedSecret},
        [Parameter(Position = 60, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopifyAccessToken},
        [Parameter(Position = 61, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopifyApiKey},
        [Parameter(Position = 62, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopifyApiPassword},
        [Parameter(Position = 63, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopifySharedSecret},
        [Parameter(Position = 64, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeePartnerId},
        [Parameter(Position = 65, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeePartnerKey},
        [Parameter(Position = 66, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeeShopId},
        [Parameter(Position = 67, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeeRefreshToken},
        [Parameter(Position = 68, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeeRegion},
        [Parameter(Position = 69, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopeeEnvironment},
        [Parameter(Position = 70, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplazzaAccessToken},
        [Parameter(Position = 71, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShoplazzaSharedSecret},
        [Parameter(Position = 72, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MivaAccessToken},
        [Parameter(Position = 73, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MivaSignature},
        [Parameter(Position = 74, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopwareAccessKey},
        [Parameter(Position = 75, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${UnasApiKey},
        [Parameter(Position = 76, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopwareApiKey},
        [Parameter(Position = 77, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ShopwareApiSecret},
        [Parameter(Position = 78, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcartelUserName},
        [Parameter(Position = 79, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BigcartelPassword},
        [Parameter(Position = 80, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BricklinkConsumerKey},
        [Parameter(Position = 81, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BricklinkConsumerSecret},
        [Parameter(Position = 82, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BricklinkToken},
        [Parameter(Position = 83, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${BricklinkTokenSecret},
        [Parameter(Position = 84, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${VolusionLogin},
        [Parameter(Position = 85, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${VolusionPassword},
        [Parameter(Position = 86, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WalmartClientId},
        [Parameter(Position = 87, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WalmartClientSecret},
        [Parameter(Position = 88, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WalmartEnvironment},
        [Parameter(Position = 89, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WalmartChannelType},
        [Parameter(Position = 90, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WalmartRegion},
        [Parameter(Position = 91, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquareClientId},
        [Parameter(Position = 92, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquareClientSecret},
        [Parameter(Position = 93, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquareRefreshToken},
        [Parameter(Position = 94, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquarespaceApiKey},
        [Parameter(Position = 95, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquarespaceClientId},
        [Parameter(Position = 96, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquarespaceClientSecret},
        [Parameter(Position = 97, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquarespaceAccessToken},
        [Parameter(Position = 98, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SquarespaceRefreshToken},
        [Parameter(Position = 99, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${HybrisClientId},
        [Parameter(Position = 100, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${HybrisClientSecret},
        [Parameter(Position = 101, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${HybrisUsername},
        [Parameter(Position = 102, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${HybrisPassword},
        [Parameter(Position = 103, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String[]]
        ${HybrisWebsites},
        [Parameter(Position = 104, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LightspeedApiKey},
        [Parameter(Position = 105, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${LightspeedApiSecret},
        [Parameter(Position = 106, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CommercehqApiKey},
        [Parameter(Position = 107, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CommercehqApiPassword},
        [Parameter(Position = 108, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WcConsumerKey},
        [Parameter(Position = 109, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WcConsumerSecret},
        [Parameter(Position = 110, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MagentoConsumerKey},
        [Parameter(Position = 111, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MagentoConsumerSecret},
        [Parameter(Position = 112, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MagentoAccessToken},
        [Parameter(Position = 113, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MagentoTokenSecret},
        [Parameter(Position = 114, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${PrestashopWebserviceKey},
        [Parameter(Position = 115, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WixAppId},
        [Parameter(Position = 116, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WixAppSecretKey},
        [Parameter(Position = 117, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WixInstanceId},
        [Parameter(Position = 118, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${WixRefreshToken},
        [Parameter(Position = 119, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MercadoLibreAppId},
        [Parameter(Position = 120, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MercadoLibreAppSecretKey},
        [Parameter(Position = 121, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MercadoLibreRefreshToken},
        [Parameter(Position = 122, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${ZidClientId},
        [Parameter(Position = 123, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZidClientSecret},
        [Parameter(Position = 124, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZidAccessToken},
        [Parameter(Position = 125, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZidAuthorization},
        [Parameter(Position = 126, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZidRefreshToken},
        [Parameter(Position = 127, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FlipkartClientId},
        [Parameter(Position = 128, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${FlipkartClientSecret},
        [Parameter(Position = 129, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AllegroClientId},
        [Parameter(Position = 130, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AllegroClientSecret},
        [Parameter(Position = 131, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AllegroAccessToken},
        [Parameter(Position = 132, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AllegroRefreshToken},
        [Parameter(Position = 133, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${AllegroEnvironment},
        [Parameter(Position = 134, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZohoClientId},
        [Parameter(Position = 135, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZohoClientSecret},
        [Parameter(Position = 136, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZohoRefreshToken},
        [Parameter(Position = 137, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ZohoRegion},
        [Parameter(Position = 138, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${TiendanubeUserId},
        [Parameter(Position = 139, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiendanubeAccessToken},
        [Parameter(Position = 140, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiendanubeClientSecret},
        [Parameter(Position = 141, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoClientId},
        [Parameter(Position = 142, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoClientSecret},
        [Parameter(Position = 143, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoAppId},
        [Parameter(Position = 144, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoRefreshToken},
        [Parameter(Position = 145, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoEnvironment},
        [Parameter(Position = 146, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${OttoAccessToken},
        [Parameter(Position = 147, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiktokshopAppKey},
        [Parameter(Position = 148, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiktokshopAppSecret},
        [Parameter(Position = 149, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiktokshopRefreshToken},
        [Parameter(Position = 150, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TiktokshopAccessToken},
        [Parameter(Position = 151, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SallaClientId},
        [Parameter(Position = 152, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SallaClientSecret},
        [Parameter(Position = 153, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SallaRefreshToken},
        [Parameter(Position = 154, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${SallaAccessToken},
        [Parameter(Position = 155, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TemuAppKey},
        [Parameter(Position = 156, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TemuAppSecret},
        [Parameter(Position = 157, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TemuAccessToken},
        [Parameter(Position = 158, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TemuRegion},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccountConfigUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/account.config.update.json'

        if ($ReplaceParameters) {
            $LocalVarQueryParameters['replace_parameters'] = $ReplaceParameters
        }

        if ($NewStoreUrl) {
            $LocalVarQueryParameters['new_store_url'] = $NewStoreUrl
        }

        if ($NewStoreKey) {
            $LocalVarQueryParameters['new_store_key'] = $NewStoreKey
        }

        if ($BridgeUrl) {
            $LocalVarQueryParameters['bridge_url'] = $BridgeUrl
        }

        if ($StoreRoot) {
            $LocalVarQueryParameters['store_root'] = $StoreRoot
        }

        if ($DbTablesPrefix) {
            $LocalVarQueryParameters['db_tables_prefix'] = $DbTablesPrefix
        }

        if ($UserAgent) {
            $LocalVarQueryParameters['user_agent'] = $UserAgent
        }

        if ($Var3dcartPrivateKey) {
            $LocalVarQueryParameters['3dcart_private_key'] = $Var3dcartPrivateKey
        }

        if ($Var3dcartAccessToken) {
            $LocalVarQueryParameters['3dcart_access_token'] = $Var3dcartAccessToken
        }

        if ($Var3dcartapiApiKey) {
            $LocalVarQueryParameters['3dcartapi_api_key'] = $Var3dcartapiApiKey
        }

        if ($AmazonSpClientId) {
            $LocalVarQueryParameters['amazon_sp_client_id'] = $AmazonSpClientId
        }

        if ($AmazonSpClientSecret) {
            $LocalVarQueryParameters['amazon_sp_client_secret'] = $AmazonSpClientSecret
        }

        if ($AmazonSpRefreshToken) {
            $LocalVarQueryParameters['amazon_sp_refresh_token'] = $AmazonSpRefreshToken
        }

        if ($AmazonSpAwsRegion) {
            $LocalVarQueryParameters['amazon_sp_aws_region'] = $AmazonSpAwsRegion
        }

        if ($AmazonSpApiEnvironment) {
            $LocalVarQueryParameters['amazon_sp_api_environment'] = $AmazonSpApiEnvironment
        }

        if ($AmazonSellerId) {
            $LocalVarQueryParameters['amazon_seller_id'] = $AmazonSellerId
        }

        if ($AspdotnetstorefrontApiUser) {
            $LocalVarQueryParameters['aspdotnetstorefront_api_user'] = $AspdotnetstorefrontApiUser
        }

        if ($AspdotnetstorefrontApiPass) {
            $LocalVarQueryParameters['aspdotnetstorefront_api_pass'] = $AspdotnetstorefrontApiPass
        }

        if ($BigcommerceapiAdminAccount) {
            $LocalVarQueryParameters['bigcommerceapi_admin_account'] = $BigcommerceapiAdminAccount
        }

        if ($BigcommerceapiApiPath) {
            $LocalVarQueryParameters['bigcommerceapi_api_path'] = $BigcommerceapiApiPath
        }

        if ($BigcommerceapiApiKey) {
            $LocalVarQueryParameters['bigcommerceapi_api_key'] = $BigcommerceapiApiKey
        }

        if ($BigcommerceapiClientId) {
            $LocalVarQueryParameters['bigcommerceapi_client_id'] = $BigcommerceapiClientId
        }

        if ($BigcommerceapiAccessToken) {
            $LocalVarQueryParameters['bigcommerceapi_access_token'] = $BigcommerceapiAccessToken
        }

        if ($BigcommerceapiContext) {
            $LocalVarQueryParameters['bigcommerceapi_context'] = $BigcommerceapiContext
        }

        if ($BolApiKey) {
            $LocalVarQueryParameters['bol_api_key'] = $BolApiKey
        }

        if ($BolApiSecret) {
            $LocalVarQueryParameters['bol_api_secret'] = $BolApiSecret
        }

        if ($BolRetailerId) {
            $LocalVarQueryParameters['bol_retailer_id'] = $BolRetailerId
        }

        if ($DemandwareClientId) {
            $LocalVarQueryParameters['demandware_client_id'] = $DemandwareClientId
        }

        if ($DemandwareApiPassword) {
            $LocalVarQueryParameters['demandware_api_password'] = $DemandwareApiPassword
        }

        if ($DemandwareUserName) {
            $LocalVarQueryParameters['demandware_user_name'] = $DemandwareUserName
        }

        if ($DemandwareUserPassword) {
            $LocalVarQueryParameters['demandware_user_password'] = $DemandwareUserPassword
        }

        if ($EbayClientId) {
            $LocalVarQueryParameters['ebay_client_id'] = $EbayClientId
        }

        if ($EbayClientSecret) {
            $LocalVarQueryParameters['ebay_client_secret'] = $EbayClientSecret
        }

        if ($EbayRuname) {
            $LocalVarQueryParameters['ebay_runame'] = $EbayRuname
        }

        if ($EbayAccessToken) {
            $LocalVarQueryParameters['ebay_access_token'] = $EbayAccessToken
        }

        if ($EbayRefreshToken) {
            $LocalVarQueryParameters['ebay_refresh_token'] = $EbayRefreshToken
        }

        if ($EbayEnvironment) {
            $LocalVarQueryParameters['ebay_environment'] = $EbayEnvironment
        }

        if ($EbaySiteId) {
            $LocalVarQueryParameters['ebay_site_id'] = $EbaySiteId
        }

        if ($EcwidAcessToken) {
            $LocalVarQueryParameters['ecwid_acess_token'] = $EcwidAcessToken
        }

        if ($EcwidStoreId) {
            $LocalVarQueryParameters['ecwid_store_id'] = $EcwidStoreId
        }

        if ($LazadaAppId) {
            $LocalVarQueryParameters['lazada_app_id'] = $LazadaAppId
        }

        if ($LazadaAppSecret) {
            $LocalVarQueryParameters['lazada_app_secret'] = $LazadaAppSecret
        }

        if ($LazadaRefreshToken) {
            $LocalVarQueryParameters['lazada_refresh_token'] = $LazadaRefreshToken
        }

        if ($LazadaRegion) {
            $LocalVarQueryParameters['lazada_region'] = $LazadaRegion
        }

        if ($EtsyKeystring) {
            $LocalVarQueryParameters['etsy_keystring'] = $EtsyKeystring
        }

        if ($EtsySharedSecret) {
            $LocalVarQueryParameters['etsy_shared_secret'] = $EtsySharedSecret
        }

        if ($EtsyAccessToken) {
            $LocalVarQueryParameters['etsy_access_token'] = $EtsyAccessToken
        }

        if ($EtsyTokenSecret) {
            $LocalVarQueryParameters['etsy_token_secret'] = $EtsyTokenSecret
        }

        if ($EtsyClientId) {
            $LocalVarQueryParameters['etsy_client_id'] = $EtsyClientId
        }

        if ($EtsyRefreshToken) {
            $LocalVarQueryParameters['etsy_refresh_token'] = $EtsyRefreshToken
        }

        if ($FacebookAppId) {
            $LocalVarQueryParameters['facebook_app_id'] = $FacebookAppId
        }

        if ($FacebookAppSecret) {
            $LocalVarQueryParameters['facebook_app_secret'] = $FacebookAppSecret
        }

        if ($FacebookAccessToken) {
            $LocalVarQueryParameters['facebook_access_token'] = $FacebookAccessToken
        }

        if ($FacebookBusinessId) {
            $LocalVarQueryParameters['facebook_business_id'] = $FacebookBusinessId
        }

        if ($NetoApiKey) {
            $LocalVarQueryParameters['neto_api_key'] = $NetoApiKey
        }

        if ($NetoApiUsername) {
            $LocalVarQueryParameters['neto_api_username'] = $NetoApiUsername
        }

        if ($ShoplineAccessToken) {
            $LocalVarQueryParameters['shopline_access_token'] = $ShoplineAccessToken
        }

        if ($ShoplineAppKey) {
            $LocalVarQueryParameters['shopline_app_key'] = $ShoplineAppKey
        }

        if ($ShoplineAppSecret) {
            $LocalVarQueryParameters['shopline_app_secret'] = $ShoplineAppSecret
        }

        if ($ShoplineSharedSecret) {
            $LocalVarQueryParameters['shopline_shared_secret'] = $ShoplineSharedSecret
        }

        if ($ShopifyAccessToken) {
            $LocalVarQueryParameters['shopify_access_token'] = $ShopifyAccessToken
        }

        if ($ShopifyApiKey) {
            $LocalVarQueryParameters['shopify_api_key'] = $ShopifyApiKey
        }

        if ($ShopifyApiPassword) {
            $LocalVarQueryParameters['shopify_api_password'] = $ShopifyApiPassword
        }

        if ($ShopifySharedSecret) {
            $LocalVarQueryParameters['shopify_shared_secret'] = $ShopifySharedSecret
        }

        if ($ShopeePartnerId) {
            $LocalVarQueryParameters['shopee_partner_id'] = $ShopeePartnerId
        }

        if ($ShopeePartnerKey) {
            $LocalVarQueryParameters['shopee_partner_key'] = $ShopeePartnerKey
        }

        if ($ShopeeShopId) {
            $LocalVarQueryParameters['shopee_shop_id'] = $ShopeeShopId
        }

        if ($ShopeeRefreshToken) {
            $LocalVarQueryParameters['shopee_refresh_token'] = $ShopeeRefreshToken
        }

        if ($ShopeeRegion) {
            $LocalVarQueryParameters['shopee_region'] = $ShopeeRegion
        }

        if ($ShopeeEnvironment) {
            $LocalVarQueryParameters['shopee_environment'] = $ShopeeEnvironment
        }

        if ($ShoplazzaAccessToken) {
            $LocalVarQueryParameters['shoplazza_access_token'] = $ShoplazzaAccessToken
        }

        if ($ShoplazzaSharedSecret) {
            $LocalVarQueryParameters['shoplazza_shared_secret'] = $ShoplazzaSharedSecret
        }

        if ($MivaAccessToken) {
            $LocalVarQueryParameters['miva_access_token'] = $MivaAccessToken
        }

        if ($MivaSignature) {
            $LocalVarQueryParameters['miva_signature'] = $MivaSignature
        }

        if ($ShopwareAccessKey) {
            $LocalVarQueryParameters['shopware_access_key'] = $ShopwareAccessKey
        }

        if ($UnasApiKey) {
            $LocalVarQueryParameters['unas_api_key'] = $UnasApiKey
        }

        if ($ShopwareApiKey) {
            $LocalVarQueryParameters['shopware_api_key'] = $ShopwareApiKey
        }

        if ($ShopwareApiSecret) {
            $LocalVarQueryParameters['shopware_api_secret'] = $ShopwareApiSecret
        }

        if ($BigcartelUserName) {
            $LocalVarQueryParameters['bigcartel_user_name'] = $BigcartelUserName
        }

        if ($BigcartelPassword) {
            $LocalVarQueryParameters['bigcartel_password'] = $BigcartelPassword
        }

        if ($BricklinkConsumerKey) {
            $LocalVarQueryParameters['bricklink_consumer_key'] = $BricklinkConsumerKey
        }

        if ($BricklinkConsumerSecret) {
            $LocalVarQueryParameters['bricklink_consumer_secret'] = $BricklinkConsumerSecret
        }

        if ($BricklinkToken) {
            $LocalVarQueryParameters['bricklink_token'] = $BricklinkToken
        }

        if ($BricklinkTokenSecret) {
            $LocalVarQueryParameters['bricklink_token_secret'] = $BricklinkTokenSecret
        }

        if ($VolusionLogin) {
            $LocalVarQueryParameters['volusion_login'] = $VolusionLogin
        }

        if ($VolusionPassword) {
            $LocalVarQueryParameters['volusion_password'] = $VolusionPassword
        }

        if ($WalmartClientId) {
            $LocalVarQueryParameters['walmart_client_id'] = $WalmartClientId
        }

        if ($WalmartClientSecret) {
            $LocalVarQueryParameters['walmart_client_secret'] = $WalmartClientSecret
        }

        if ($WalmartEnvironment) {
            $LocalVarQueryParameters['walmart_environment'] = $WalmartEnvironment
        }

        if ($WalmartChannelType) {
            $LocalVarQueryParameters['walmart_channel_type'] = $WalmartChannelType
        }

        if ($WalmartRegion) {
            $LocalVarQueryParameters['walmart_region'] = $WalmartRegion
        }

        if ($SquareClientId) {
            $LocalVarQueryParameters['square_client_id'] = $SquareClientId
        }

        if ($SquareClientSecret) {
            $LocalVarQueryParameters['square_client_secret'] = $SquareClientSecret
        }

        if ($SquareRefreshToken) {
            $LocalVarQueryParameters['square_refresh_token'] = $SquareRefreshToken
        }

        if ($SquarespaceApiKey) {
            $LocalVarQueryParameters['squarespace_api_key'] = $SquarespaceApiKey
        }

        if ($SquarespaceClientId) {
            $LocalVarQueryParameters['squarespace_client_id'] = $SquarespaceClientId
        }

        if ($SquarespaceClientSecret) {
            $LocalVarQueryParameters['squarespace_client_secret'] = $SquarespaceClientSecret
        }

        if ($SquarespaceAccessToken) {
            $LocalVarQueryParameters['squarespace_access_token'] = $SquarespaceAccessToken
        }

        if ($SquarespaceRefreshToken) {
            $LocalVarQueryParameters['squarespace_refresh_token'] = $SquarespaceRefreshToken
        }

        if ($HybrisClientId) {
            $LocalVarQueryParameters['hybris_client_id'] = $HybrisClientId
        }

        if ($HybrisClientSecret) {
            $LocalVarQueryParameters['hybris_client_secret'] = $HybrisClientSecret
        }

        if ($HybrisUsername) {
            $LocalVarQueryParameters['hybris_username'] = $HybrisUsername
        }

        if ($HybrisPassword) {
            $LocalVarQueryParameters['hybris_password'] = $HybrisPassword
        }

        if ($HybrisWebsites) {
            $LocalVarQueryParameters['hybris_websites'] = $HybrisWebsites
        }

        if ($LightspeedApiKey) {
            $LocalVarQueryParameters['lightspeed_api_key'] = $LightspeedApiKey
        }

        if ($LightspeedApiSecret) {
            $LocalVarQueryParameters['lightspeed_api_secret'] = $LightspeedApiSecret
        }

        if ($CommercehqApiKey) {
            $LocalVarQueryParameters['commercehq_api_key'] = $CommercehqApiKey
        }

        if ($CommercehqApiPassword) {
            $LocalVarQueryParameters['commercehq_api_password'] = $CommercehqApiPassword
        }

        if ($WcConsumerKey) {
            $LocalVarQueryParameters['wc_consumer_key'] = $WcConsumerKey
        }

        if ($WcConsumerSecret) {
            $LocalVarQueryParameters['wc_consumer_secret'] = $WcConsumerSecret
        }

        if ($MagentoConsumerKey) {
            $LocalVarQueryParameters['magento_consumer_key'] = $MagentoConsumerKey
        }

        if ($MagentoConsumerSecret) {
            $LocalVarQueryParameters['magento_consumer_secret'] = $MagentoConsumerSecret
        }

        if ($MagentoAccessToken) {
            $LocalVarQueryParameters['magento_access_token'] = $MagentoAccessToken
        }

        if ($MagentoTokenSecret) {
            $LocalVarQueryParameters['magento_token_secret'] = $MagentoTokenSecret
        }

        if ($PrestashopWebserviceKey) {
            $LocalVarQueryParameters['prestashop_webservice_key'] = $PrestashopWebserviceKey
        }

        if ($WixAppId) {
            $LocalVarQueryParameters['wix_app_id'] = $WixAppId
        }

        if ($WixAppSecretKey) {
            $LocalVarQueryParameters['wix_app_secret_key'] = $WixAppSecretKey
        }

        if ($WixInstanceId) {
            $LocalVarQueryParameters['wix_instance_id'] = $WixInstanceId
        }

        if ($WixRefreshToken) {
            $LocalVarQueryParameters['wix_refresh_token'] = $WixRefreshToken
        }

        if ($MercadoLibreAppId) {
            $LocalVarQueryParameters['mercado_libre_app_id'] = $MercadoLibreAppId
        }

        if ($MercadoLibreAppSecretKey) {
            $LocalVarQueryParameters['mercado_libre_app_secret_key'] = $MercadoLibreAppSecretKey
        }

        if ($MercadoLibreRefreshToken) {
            $LocalVarQueryParameters['mercado_libre_refresh_token'] = $MercadoLibreRefreshToken
        }

        if ($ZidClientId) {
            $LocalVarQueryParameters['zid_client_id'] = $ZidClientId
        }

        if ($ZidClientSecret) {
            $LocalVarQueryParameters['zid_client_secret'] = $ZidClientSecret
        }

        if ($ZidAccessToken) {
            $LocalVarQueryParameters['zid_access_token'] = $ZidAccessToken
        }

        if ($ZidAuthorization) {
            $LocalVarQueryParameters['zid_authorization'] = $ZidAuthorization
        }

        if ($ZidRefreshToken) {
            $LocalVarQueryParameters['zid_refresh_token'] = $ZidRefreshToken
        }

        if ($FlipkartClientId) {
            $LocalVarQueryParameters['flipkart_client_id'] = $FlipkartClientId
        }

        if ($FlipkartClientSecret) {
            $LocalVarQueryParameters['flipkart_client_secret'] = $FlipkartClientSecret
        }

        if ($AllegroClientId) {
            $LocalVarQueryParameters['allegro_client_id'] = $AllegroClientId
        }

        if ($AllegroClientSecret) {
            $LocalVarQueryParameters['allegro_client_secret'] = $AllegroClientSecret
        }

        if ($AllegroAccessToken) {
            $LocalVarQueryParameters['allegro_access_token'] = $AllegroAccessToken
        }

        if ($AllegroRefreshToken) {
            $LocalVarQueryParameters['allegro_refresh_token'] = $AllegroRefreshToken
        }

        if ($AllegroEnvironment) {
            $LocalVarQueryParameters['allegro_environment'] = $AllegroEnvironment
        }

        if ($ZohoClientId) {
            $LocalVarQueryParameters['zoho_client_id'] = $ZohoClientId
        }

        if ($ZohoClientSecret) {
            $LocalVarQueryParameters['zoho_client_secret'] = $ZohoClientSecret
        }

        if ($ZohoRefreshToken) {
            $LocalVarQueryParameters['zoho_refresh_token'] = $ZohoRefreshToken
        }

        if ($ZohoRegion) {
            $LocalVarQueryParameters['zoho_region'] = $ZohoRegion
        }

        if ($TiendanubeUserId) {
            $LocalVarQueryParameters['tiendanube_user_id'] = $TiendanubeUserId
        }

        if ($TiendanubeAccessToken) {
            $LocalVarQueryParameters['tiendanube_access_token'] = $TiendanubeAccessToken
        }

        if ($TiendanubeClientSecret) {
            $LocalVarQueryParameters['tiendanube_client_secret'] = $TiendanubeClientSecret
        }

        if ($OttoClientId) {
            $LocalVarQueryParameters['otto_client_id'] = $OttoClientId
        }

        if ($OttoClientSecret) {
            $LocalVarQueryParameters['otto_client_secret'] = $OttoClientSecret
        }

        if ($OttoAppId) {
            $LocalVarQueryParameters['otto_app_id'] = $OttoAppId
        }

        if ($OttoRefreshToken) {
            $LocalVarQueryParameters['otto_refresh_token'] = $OttoRefreshToken
        }

        if ($OttoEnvironment) {
            $LocalVarQueryParameters['otto_environment'] = $OttoEnvironment
        }

        if ($OttoAccessToken) {
            $LocalVarQueryParameters['otto_access_token'] = $OttoAccessToken
        }

        if ($TiktokshopAppKey) {
            $LocalVarQueryParameters['tiktokshop_app_key'] = $TiktokshopAppKey
        }

        if ($TiktokshopAppSecret) {
            $LocalVarQueryParameters['tiktokshop_app_secret'] = $TiktokshopAppSecret
        }

        if ($TiktokshopRefreshToken) {
            $LocalVarQueryParameters['tiktokshop_refresh_token'] = $TiktokshopRefreshToken
        }

        if ($TiktokshopAccessToken) {
            $LocalVarQueryParameters['tiktokshop_access_token'] = $TiktokshopAccessToken
        }

        if ($SallaClientId) {
            $LocalVarQueryParameters['salla_client_id'] = $SallaClientId
        }

        if ($SallaClientSecret) {
            $LocalVarQueryParameters['salla_client_secret'] = $SallaClientSecret
        }

        if ($SallaRefreshToken) {
            $LocalVarQueryParameters['salla_refresh_token'] = $SallaRefreshToken
        }

        if ($SallaAccessToken) {
            $LocalVarQueryParameters['salla_access_token'] = $SallaAccessToken
        }

        if ($TemuAppKey) {
            $LocalVarQueryParameters['temu_app_key'] = $TemuAppKey
        }

        if ($TemuAppSecret) {
            $LocalVarQueryParameters['temu_app_secret'] = $TemuAppSecret
        }

        if ($TemuAccessToken) {
            $LocalVarQueryParameters['temu_access_token'] = $TemuAccessToken
        }

        if ($TemuRegion) {
            $LocalVarQueryParameters['temu_region'] = $TemuRegion
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-store-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-store-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-store-key"]) {
            $LocalVarHeaderParameters['x-store-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-store-key"]
            Write-Verbose ("Using API key 'x-store-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'PUT' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccountConfigUpdate200Response" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

account.failed_webhooks

.DESCRIPTION

No description available.

.PARAMETER Start
This parameter sets the number from which you want to get entities

.PARAMETER Count
This parameter sets the entity amount that has to be retrieved. Max allowed count=250

.PARAMETER Ids
List of сomma-separated webhook ids

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccountFailedWebhooks200Response
#>
function Invoke-AccountFailedWebhooks {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${Start},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${Count},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Ids},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccountFailedWebhooks' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/account.failed_webhooks.json'

        if ($Start) {
            $LocalVarQueryParameters['start'] = $Start
        }

        if ($Count) {
            $LocalVarQueryParameters['count'] = $Count
        }

        if ($Ids) {
            $LocalVarQueryParameters['ids'] = $Ids
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccountFailedWebhooks200Response" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

account.supported_platforms

.DESCRIPTION

No description available.

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccountSupportedPlatforms200Response
#>
function Invoke-AccountSupportedPlatforms {
    [CmdletBinding()]
    Param (
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccountSupportedPlatforms' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/account.supported_platforms.json'

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccountSupportedPlatforms200Response" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

