#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

marketplace.product.find

.DESCRIPTION

No description available.

.PARAMETER Count
This parameter sets the entity amount that has to be retrieved. Max allowed count=250

.PARAMETER PageCursor
Used to retrieve entities via cursor-based pagination (it can't be used with any other filtering parameter)

.PARAMETER Keyword
Defines search keyword

.PARAMETER CategoriesIds
Defines product add that is specified by comma-separated categories id

.PARAMETER StoreId
Store Id

.PARAMETER Asin
Amazon Standard Identification Number.

.PARAMETER Ean
European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products.

.PARAMETER Gtin
Global Trade Item Number. An GTIN is an identifier for trade items.

.PARAMETER Upc
Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products.

.PARAMETER Mpn
Manufacturer Part Number. A MPN is an identifier of a particular part design or material used.

.PARAMETER Isbn
International Standard Book Number. An ISBN is a unique identifier for books.

.PARAMETER ResponseFields
Set this parameter in order to choose which entity fields you want to retrieve

.PARAMETER Params
Set this parameter in order to choose which entity fields you want to retrieve

.PARAMETER Exclude
Set this parameter in order to choose which entity fields you want to ignore. Works only if parameter `params` equal force_all

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

ModelResponseMarketplaceProductFind
#>
function Invoke-MarketplaceProductFind {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [System.Nullable[Int32]]
        ${Count},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${PageCursor},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Keyword},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CategoriesIds},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${StoreId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Asin},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Ean},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Gtin},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Upc},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Mpn},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Isbn},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ResponseFields},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Params},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Exclude},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-MarketplaceProductFind' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/marketplace.product.find.json'

        if ($Count) {
            $LocalVarQueryParameters['count'] = $Count
        }

        if ($PageCursor) {
            $LocalVarQueryParameters['page_cursor'] = $PageCursor
        }

        if ($Keyword) {
            $LocalVarQueryParameters['keyword'] = $Keyword
        }

        if ($CategoriesIds) {
            $LocalVarQueryParameters['categories_ids'] = $CategoriesIds
        }

        if ($StoreId) {
            $LocalVarQueryParameters['store_id'] = $StoreId
        }

        if ($Asin) {
            $LocalVarQueryParameters['asin'] = $Asin
        }

        if ($Ean) {
            $LocalVarQueryParameters['ean'] = $Ean
        }

        if ($Gtin) {
            $LocalVarQueryParameters['gtin'] = $Gtin
        }

        if ($Upc) {
            $LocalVarQueryParameters['upc'] = $Upc
        }

        if ($Mpn) {
            $LocalVarQueryParameters['mpn'] = $Mpn
        }

        if ($Isbn) {
            $LocalVarQueryParameters['isbn'] = $Isbn
        }

        if ($ResponseFields) {
            $LocalVarQueryParameters['response_fields'] = $ResponseFields
        }

        if ($Params) {
            $LocalVarQueryParameters['params'] = $Params
        }

        if ($Exclude) {
            $LocalVarQueryParameters['exclude'] = $Exclude
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-store-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-store-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-store-key"]) {
            $LocalVarHeaderParameters['x-store-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-store-key"]
            Write-Verbose ("Using API key 'x-store-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        if ($Configuration["ApiKeyPrefix"] -and $Configuration["ApiKeyPrefix"]["x-api-key"]) {
            $apiKeyPrefix = $Configuration["ApiKeyPrefix"]["x-api-key"]
        } else {
            $apiKeyPrefix = ""
        }
        if ($Configuration["ApiKey"] -and $Configuration["ApiKey"]["x-api-key"]) {
            $LocalVarHeaderParameters['x-api-key'] = $apiKeyPrefix + $Configuration["ApiKey"]["x-api-key"]
            Write-Verbose ("Using API key 'x-api-key' in the header for authentication in {0}" -f $MyInvocation.MyCommand)
        }

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "ModelResponseMarketplaceProductFind" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

