#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER UpdatedItems
No description available.
.OUTPUTS

AccountConfigUpdate200ResponseResult<PSCustomObject>
#>

function Initialize-AccountConfigUpdate200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${UpdatedItems}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AccountConfigUpdate200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "updated_items" = ${UpdatedItems}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccountConfigUpdate200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccountConfigUpdate200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccountConfigUpdate200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToAccountConfigUpdate200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AccountConfigUpdate200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccountConfigUpdate200ResponseResult
        $AllProperties = ("updated_items")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updated_items"))) { #optional property not found
            $UpdatedItems = $null
        } else {
            $UpdatedItems = $JsonParameters.PSobject.Properties["updated_items"].value
        }

        $PSO = [PSCustomObject]@{
            "updated_items" = ${UpdatedItems}
        }

        return $PSO
    }

}

