#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AllFailedWebhook
No description available.
.PARAMETER Webhook
No description available.
.OUTPUTS

AccountFailedWebhooks200ResponseResult<PSCustomObject>
#>

function Initialize-AccountFailedWebhooks200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AllFailedWebhook},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Webhook}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AccountFailedWebhooks200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "all_failed_webhook" = ${AllFailedWebhook}
            "webhook" = ${Webhook}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccountFailedWebhooks200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccountFailedWebhooks200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccountFailedWebhooks200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToAccountFailedWebhooks200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AccountFailedWebhooks200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccountFailedWebhooks200ResponseResult
        $AllProperties = ("all_failed_webhook", "webhook")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "all_failed_webhook"))) { #optional property not found
            $AllFailedWebhook = $null
        } else {
            $AllFailedWebhook = $JsonParameters.PSobject.Properties["all_failed_webhook"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "webhook"))) { #optional property not found
            $Webhook = $null
        } else {
            $Webhook = $JsonParameters.PSobject.Properties["webhook"].value
        }

        $PSO = [PSCustomObject]@{
            "all_failed_webhook" = ${AllFailedWebhook}
            "webhook" = ${Webhook}
        }

        return $PSO
    }

}

