#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER ValueId
No description available.
.PARAMETER Name
No description available.
.PARAMETER Value
No description available.
.PARAMETER UsedInCombination
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

BasketItemOption<PSCustomObject>
#>

function Initialize-BasketItemOption {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ValueId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Value},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${UsedInCombination},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => BasketItemOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "value_id" = ${ValueId}
            "name" = ${Name}
            "value" = ${Value}
            "used_in_combination" = ${UsedInCombination}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BasketItemOption<PSCustomObject>

.DESCRIPTION

Convert from JSON to BasketItemOption<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BasketItemOption<PSCustomObject>
#>
function ConvertFrom-JsonToBasketItemOption {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => BasketItemOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BasketItemOption
        $AllProperties = ("id", "value_id", "name", "value", "used_in_combination", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value_id"))) { #optional property not found
            $ValueId = $null
        } else {
            $ValueId = $JsonParameters.PSobject.Properties["value_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "used_in_combination"))) { #optional property not found
            $UsedInCombination = $null
        } else {
            $UsedInCombination = $JsonParameters.PSobject.Properties["used_in_combination"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "value_id" = ${ValueId}
            "name" = ${Name}
            "value" = ${Value}
            "used_in_combination" = ${UsedInCombination}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

