#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Name
No description available.
.PARAMETER HandlingFee
No description available.
.PARAMETER HandlingEnabled
No description available.
.PARAMETER HandlingType
No description available.
.PARAMETER DefaultPrice
No description available.
.PARAMETER DefaultPriceType
No description available.
.PARAMETER Type
No description available.
.PARAMETER Enabled
No description available.
.PARAMETER MinOrderAmount
No description available.
.PARAMETER Rates
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

CartShippingMethod<PSCustomObject>
#>

function Initialize-CartShippingMethod {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HandlingFee},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HandlingEnabled},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HandlingType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultPrice},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultPriceType},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Enabled},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MinOrderAmount},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Rates},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CartShippingMethod' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "handling_fee" = ${HandlingFee}
            "handling_enabled" = ${HandlingEnabled}
            "handling_type" = ${HandlingType}
            "default_price" = ${DefaultPrice}
            "default_price_type" = ${DefaultPriceType}
            "type" = ${Type}
            "enabled" = ${Enabled}
            "min_order_amount" = ${MinOrderAmount}
            "rates" = ${Rates}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CartShippingMethod<PSCustomObject>

.DESCRIPTION

Convert from JSON to CartShippingMethod<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CartShippingMethod<PSCustomObject>
#>
function ConvertFrom-JsonToCartShippingMethod {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CartShippingMethod' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CartShippingMethod
        $AllProperties = ("name", "handling_fee", "handling_enabled", "handling_type", "default_price", "default_price_type", "type", "enabled", "min_order_amount", "rates", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "handling_fee"))) { #optional property not found
            $HandlingFee = $null
        } else {
            $HandlingFee = $JsonParameters.PSobject.Properties["handling_fee"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "handling_enabled"))) { #optional property not found
            $HandlingEnabled = $null
        } else {
            $HandlingEnabled = $JsonParameters.PSobject.Properties["handling_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "handling_type"))) { #optional property not found
            $HandlingType = $null
        } else {
            $HandlingType = $JsonParameters.PSobject.Properties["handling_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "default_price"))) { #optional property not found
            $DefaultPrice = $null
        } else {
            $DefaultPrice = $JsonParameters.PSobject.Properties["default_price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "default_price_type"))) { #optional property not found
            $DefaultPriceType = $null
        } else {
            $DefaultPriceType = $JsonParameters.PSobject.Properties["default_price_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "min_order_amount"))) { #optional property not found
            $MinOrderAmount = $null
        } else {
            $MinOrderAmount = $JsonParameters.PSobject.Properties["min_order_amount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rates"))) { #optional property not found
            $Rates = $null
        } else {
            $Rates = $JsonParameters.PSobject.Properties["rates"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "handling_fee" = ${HandlingFee}
            "handling_enabled" = ${HandlingEnabled}
            "handling_type" = ${HandlingType}
            "default_price" = ${DefaultPrice}
            "default_price_type" = ${DefaultPriceType}
            "type" = ${Type}
            "enabled" = ${Enabled}
            "min_order_amount" = ${MinOrderAmount}
            "rates" = ${Rates}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

