#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CatalogPriceRulesCount
No description available.
.OUTPUTS

CartCatalogPriceRulesCount200ResponseResult<PSCustomObject>
#>

function Initialize-CartCatalogPriceRulesCount200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CatalogPriceRulesCount}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CartCatalogPriceRulesCount200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "catalog_price_rules_count" = ${CatalogPriceRulesCount}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CartCatalogPriceRulesCount200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to CartCatalogPriceRulesCount200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CartCatalogPriceRulesCount200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToCartCatalogPriceRulesCount200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CartCatalogPriceRulesCount200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CartCatalogPriceRulesCount200ResponseResult
        $AllProperties = ("catalog_price_rules_count")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "catalog_price_rules_count"))) { #optional property not found
            $CatalogPriceRulesCount = $null
        } else {
            $CatalogPriceRulesCount = $JsonParameters.PSobject.Properties["catalog_price_rules_count"].value
        }

        $PSO = [PSCustomObject]@{
            "catalog_price_rules_count" = ${CatalogPriceRulesCount}
        }

        return $PSO
    }

}

