#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER ParentId
No description available.
.PARAMETER CreatedAt
No description available.
.PARAMETER ModifiedAt
No description available.
.PARAMETER Name
No description available.
.PARAMETER ShortDescription
No description available.
.PARAMETER Description
No description available.
.PARAMETER StoresIds
No description available.
.PARAMETER Keywords
No description available.
.PARAMETER MetaDescription
No description available.
.PARAMETER MetaTitle
No description available.
.PARAMETER Avail
No description available.
.PARAMETER Path
No description available.
.PARAMETER SeoUrl
No description available.
.PARAMETER SortOrder
No description available.
.PARAMETER Images
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

Category<PSCustomObject>
#>

function Initialize-Category {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CreatedAt},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ModifiedAt},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ShortDescription},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${StoresIds},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Keywords},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MetaDescription},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MetaTitle},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Avail},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Path},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SeoUrl},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SortOrder},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Images},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Category' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "parent_id" = ${ParentId}
            "created_at" = ${CreatedAt}
            "modified_at" = ${ModifiedAt}
            "name" = ${Name}
            "short_description" = ${ShortDescription}
            "description" = ${Description}
            "stores_ids" = ${StoresIds}
            "keywords" = ${Keywords}
            "meta_description" = ${MetaDescription}
            "meta_title" = ${MetaTitle}
            "avail" = ${Avail}
            "path" = ${Path}
            "seo_url" = ${SeoUrl}
            "sort_order" = ${SortOrder}
            "images" = ${Images}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Category<PSCustomObject>

.DESCRIPTION

Convert from JSON to Category<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Category<PSCustomObject>
#>
function ConvertFrom-JsonToCategory {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Category' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Category
        $AllProperties = ("id", "parent_id", "created_at", "modified_at", "name", "short_description", "description", "stores_ids", "keywords", "meta_description", "meta_title", "avail", "path", "seo_url", "sort_order", "images", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parent_id"))) { #optional property not found
            $ParentId = $null
        } else {
            $ParentId = $JsonParameters.PSobject.Properties["parent_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "created_at"))) { #optional property not found
            $CreatedAt = $null
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["created_at"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "modified_at"))) { #optional property not found
            $ModifiedAt = $null
        } else {
            $ModifiedAt = $JsonParameters.PSobject.Properties["modified_at"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "short_description"))) { #optional property not found
            $ShortDescription = $null
        } else {
            $ShortDescription = $JsonParameters.PSobject.Properties["short_description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "stores_ids"))) { #optional property not found
            $StoresIds = $null
        } else {
            $StoresIds = $JsonParameters.PSobject.Properties["stores_ids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "keywords"))) { #optional property not found
            $Keywords = $null
        } else {
            $Keywords = $JsonParameters.PSobject.Properties["keywords"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "meta_description"))) { #optional property not found
            $MetaDescription = $null
        } else {
            $MetaDescription = $JsonParameters.PSobject.Properties["meta_description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "meta_title"))) { #optional property not found
            $MetaTitle = $null
        } else {
            $MetaTitle = $JsonParameters.PSobject.Properties["meta_title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avail"))) { #optional property not found
            $Avail = $null
        } else {
            $Avail = $JsonParameters.PSobject.Properties["avail"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "path"))) { #optional property not found
            $Path = $null
        } else {
            $Path = $JsonParameters.PSobject.Properties["path"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "seo_url"))) { #optional property not found
            $SeoUrl = $null
        } else {
            $SeoUrl = $JsonParameters.PSobject.Properties["seo_url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sort_order"))) { #optional property not found
            $SortOrder = $null
        } else {
            $SortOrder = $JsonParameters.PSobject.Properties["sort_order"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "images"))) { #optional property not found
            $Images = $null
        } else {
            $Images = $JsonParameters.PSobject.Properties["images"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "parent_id" = ${ParentId}
            "created_at" = ${CreatedAt}
            "modified_at" = ${ModifiedAt}
            "name" = ${Name}
            "short_description" = ${ShortDescription}
            "description" = ${Description}
            "stores_ids" = ${StoresIds}
            "keywords" = ${Keywords}
            "meta_description" = ${MetaDescription}
            "meta_title" = ${MetaTitle}
            "avail" = ${Avail}
            "path" = ${Path}
            "seo_url" = ${SeoUrl}
            "sort_order" = ${SortOrder}
            "images" = ${Images}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

