#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER GroupId
No description available.
.OUTPUTS

CustomerGroupAdd200ResponseResult<PSCustomObject>
#>

function Initialize-CustomerGroupAdd200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${GroupId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CustomerGroupAdd200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "group_id" = ${GroupId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomerGroupAdd200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomerGroupAdd200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomerGroupAdd200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToCustomerGroupAdd200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CustomerGroupAdd200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomerGroupAdd200ResponseResult
        $AllProperties = ("group_id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "group_id"))) { #optional property not found
            $GroupId = $null
        } else {
            $GroupId = $JsonParameters.PSobject.Properties["group_id"].value
        }

        $PSO = [PSCustomObject]@{
            "group_id" = ${GroupId}
        }

        return $PSO
    }

}

