#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CustomersCount
No description available.
.OUTPUTS

CustomerCount200ResponseResult<PSCustomObject>
#>

function Initialize-CustomerCount200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CustomersCount}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CustomerCount200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "customers_count" = ${CustomersCount}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomerCount200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomerCount200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomerCount200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToCustomerCount200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CustomerCount200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomerCount200ResponseResult
        $AllProperties = ("customers_count")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customers_count"))) { #optional property not found
            $CustomersCount = $null
        } else {
            $CustomersCount = $JsonParameters.PSobject.Properties["customers_count"].value
        }

        $PSO = [PSCustomObject]@{
            "customers_count" = ${CustomersCount}
        }

        return $PSO
    }

}

