#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DeleteItems
No description available.
.OUTPUTS

CustomerDelete200ResponseResult<PSCustomObject>
#>

function Initialize-CustomerDelete200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${DeleteItems}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CustomerDelete200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "delete_items" = ${DeleteItems}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomerDelete200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomerDelete200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomerDelete200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToCustomerDelete200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CustomerDelete200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomerDelete200ResponseResult
        $AllProperties = ("delete_items")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "delete_items"))) { #optional property not found
            $DeleteItems = $null
        } else {
            $DeleteItems = $JsonParameters.PSobject.Properties["delete_items"].value
        }

        $PSO = [PSCustomObject]@{
            "delete_items" = ${DeleteItems}
        }

        return $PSO
    }

}

