#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Code
No description available.
.PARAMETER Name
No description available.
.PARAMETER Type
No description available.
.PARAMETER CurrencyCode
No description available.
.PARAMETER Amount
No description available.
.PARAMETER InitialAmount
No description available.
.PARAMETER Status
No description available.
.PARAMETER CreatedAt
No description available.
.PARAMETER AvailTo
No description available.
.PARAMETER FreeProductIds
No description available.
.PARAMETER Message
No description available.
.PARAMETER IssuerEmail
No description available.
.PARAMETER RecipientEmail
No description available.
.PARAMETER IssuerName
No description available.
.PARAMETER RecipientName
No description available.
.PARAMETER UsageHistory
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

GiftCard<PSCustomObject>
#>

function Initialize-GiftCard {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Code},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyCode},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Amount},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${InitialAmount},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Status},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CreatedAt},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AvailTo},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FreeProductIds},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IssuerEmail},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RecipientEmail},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IssuerName},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RecipientName},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${UsageHistory},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => GiftCard' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "code" = ${Code}
            "name" = ${Name}
            "type" = ${Type}
            "currency_code" = ${CurrencyCode}
            "amount" = ${Amount}
            "initial_amount" = ${InitialAmount}
            "status" = ${Status}
            "created_at" = ${CreatedAt}
            "avail_to" = ${AvailTo}
            "free_product_ids" = ${FreeProductIds}
            "message" = ${Message}
            "issuer_email" = ${IssuerEmail}
            "recipient_email" = ${RecipientEmail}
            "issuer_name" = ${IssuerName}
            "recipient_name" = ${RecipientName}
            "usage_history" = ${UsageHistory}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GiftCard<PSCustomObject>

.DESCRIPTION

Convert from JSON to GiftCard<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GiftCard<PSCustomObject>
#>
function ConvertFrom-JsonToGiftCard {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => GiftCard' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in GiftCard
        $AllProperties = ("id", "code", "name", "type", "currency_code", "amount", "initial_amount", "status", "created_at", "avail_to", "free_product_ids", "message", "issuer_email", "recipient_email", "issuer_name", "recipient_name", "usage_history", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "code"))) { #optional property not found
            $Code = $null
        } else {
            $Code = $JsonParameters.PSobject.Properties["code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currency_code"))) { #optional property not found
            $CurrencyCode = $null
        } else {
            $CurrencyCode = $JsonParameters.PSobject.Properties["currency_code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "amount"))) { #optional property not found
            $Amount = $null
        } else {
            $Amount = $JsonParameters.PSobject.Properties["amount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "initial_amount"))) { #optional property not found
            $InitialAmount = $null
        } else {
            $InitialAmount = $JsonParameters.PSobject.Properties["initial_amount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "created_at"))) { #optional property not found
            $CreatedAt = $null
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["created_at"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avail_to"))) { #optional property not found
            $AvailTo = $null
        } else {
            $AvailTo = $JsonParameters.PSobject.Properties["avail_to"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "free_product_ids"))) { #optional property not found
            $FreeProductIds = $null
        } else {
            $FreeProductIds = $JsonParameters.PSobject.Properties["free_product_ids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issuer_email"))) { #optional property not found
            $IssuerEmail = $null
        } else {
            $IssuerEmail = $JsonParameters.PSobject.Properties["issuer_email"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recipient_email"))) { #optional property not found
            $RecipientEmail = $null
        } else {
            $RecipientEmail = $JsonParameters.PSobject.Properties["recipient_email"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issuer_name"))) { #optional property not found
            $IssuerName = $null
        } else {
            $IssuerName = $JsonParameters.PSobject.Properties["issuer_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recipient_name"))) { #optional property not found
            $RecipientName = $null
        } else {
            $RecipientName = $JsonParameters.PSobject.Properties["recipient_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "usage_history"))) { #optional property not found
            $UsageHistory = $null
        } else {
            $UsageHistory = $JsonParameters.PSobject.Properties["usage_history"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "code" = ${Code}
            "name" = ${Name}
            "type" = ${Type}
            "currency_code" = ${CurrencyCode}
            "amount" = ${Amount}
            "initial_amount" = ${InitialAmount}
            "status" = ${Status}
            "created_at" = ${CreatedAt}
            "avail_to" = ${AvailTo}
            "free_product_ids" = ${FreeProductIds}
            "message" = ${Message}
            "issuer_email" = ${IssuerEmail}
            "recipient_email" = ${RecipientEmail}
            "issuer_name" = ${IssuerName}
            "recipient_name" = ${RecipientName}
            "usage_history" = ${UsageHistory}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

