#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER HttpPath
No description available.
.PARAMETER FileName
No description available.
.PARAMETER MimeType
No description available.
.PARAMETER Size
No description available.
.PARAMETER CreateAt
No description available.
.PARAMETER ModifiedAt
No description available.
.PARAMETER Alt
No description available.
.PARAMETER Avail
No description available.
.PARAMETER SortOrder
No description available.
.PARAMETER Type
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

Image<PSCustomObject>
#>

function Initialize-Image {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HttpPath},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FileName},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MimeType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Size},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CreateAt},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ModifiedAt},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Alt},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Avail},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SortOrder},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Image' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "http_path" = ${HttpPath}
            "file_name" = ${FileName}
            "mime-type" = ${MimeType}
            "size" = ${Size}
            "create_at" = ${CreateAt}
            "modified_at" = ${ModifiedAt}
            "alt" = ${Alt}
            "avail" = ${Avail}
            "sort_order" = ${SortOrder}
            "type" = ${Type}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Image<PSCustomObject>

.DESCRIPTION

Convert from JSON to Image<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Image<PSCustomObject>
#>
function ConvertFrom-JsonToImage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Image' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Image
        $AllProperties = ("id", "http_path", "file_name", "mime-type", "size", "create_at", "modified_at", "alt", "avail", "sort_order", "type", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "http_path"))) { #optional property not found
            $HttpPath = $null
        } else {
            $HttpPath = $JsonParameters.PSobject.Properties["http_path"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "file_name"))) { #optional property not found
            $FileName = $null
        } else {
            $FileName = $JsonParameters.PSobject.Properties["file_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mime-type"))) { #optional property not found
            $MimeType = $null
        } else {
            $MimeType = $JsonParameters.PSobject.Properties["mime-type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "size"))) { #optional property not found
            $Size = $null
        } else {
            $Size = $JsonParameters.PSobject.Properties["size"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "create_at"))) { #optional property not found
            $CreateAt = $null
        } else {
            $CreateAt = $JsonParameters.PSobject.Properties["create_at"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "modified_at"))) { #optional property not found
            $ModifiedAt = $null
        } else {
            $ModifiedAt = $JsonParameters.PSobject.Properties["modified_at"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "alt"))) { #optional property not found
            $Alt = $null
        } else {
            $Alt = $JsonParameters.PSobject.Properties["alt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avail"))) { #optional property not found
            $Avail = $null
        } else {
            $Avail = $JsonParameters.PSobject.Properties["avail"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sort_order"))) { #optional property not found
            $SortOrder = $null
        } else {
            $SortOrder = $JsonParameters.PSobject.Properties["sort_order"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "http_path" = ${HttpPath}
            "file_name" = ${FileName}
            "mime-type" = ${MimeType}
            "size" = ${Size}
            "create_at" = ${CreateAt}
            "modified_at" = ${ModifiedAt}
            "alt" = ${Alt}
            "avail" = ${Avail}
            "sort_order" = ${SortOrder}
            "type" = ${Type}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

