#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ProductId
No description available.
.PARAMETER OrderProductId
No description available.
.PARAMETER Model
No description available.
.PARAMETER Name
No description available.
.PARAMETER Price
No description available.
.PARAMETER PriceIncTax
No description available.
.PARAMETER Quantity
No description available.
.PARAMETER DiscountAmount
No description available.
.PARAMETER TotalPrice
No description available.
.PARAMETER TaxPercent
No description available.
.PARAMETER TaxValue
No description available.
.PARAMETER TaxValueAfterDiscount
No description available.
.PARAMETER Options
No description available.
.PARAMETER VariantId
No description available.
.PARAMETER WeightUnit
No description available.
.PARAMETER Weight
No description available.
.PARAMETER Barcode
No description available.
.PARAMETER ParentOrderProductId
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

OrderItem<PSCustomObject>
#>

function Initialize-OrderItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderProductId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Model},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Price},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${PriceIncTax},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Quantity},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${DiscountAmount},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TotalPrice},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TaxPercent},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TaxValue},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TaxValueAfterDiscount},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Options},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VariantId},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WeightUnit},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Weight},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Barcode},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ParentOrderProductId},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "order_product_id" = ${OrderProductId}
            "model" = ${Model}
            "name" = ${Name}
            "price" = ${Price}
            "price_inc_tax" = ${PriceIncTax}
            "quantity" = ${Quantity}
            "discount_amount" = ${DiscountAmount}
            "total_price" = ${TotalPrice}
            "tax_percent" = ${TaxPercent}
            "tax_value" = ${TaxValue}
            "tax_value_after_discount" = ${TaxValueAfterDiscount}
            "options" = ${Options}
            "variant_id" = ${VariantId}
            "weight_unit" = ${WeightUnit}
            "weight" = ${Weight}
            "barcode" = ${Barcode}
            "parent_order_product_id" = ${ParentOrderProductId}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderItem<PSCustomObject>
#>
function ConvertFrom-JsonToOrderItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderItem
        $AllProperties = ("product_id", "order_product_id", "model", "name", "price", "price_inc_tax", "quantity", "discount_amount", "total_price", "tax_percent", "tax_value", "tax_value_after_discount", "options", "variant_id", "weight_unit", "weight", "barcode", "parent_order_product_id", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "product_id"))) { #optional property not found
            $ProductId = $null
        } else {
            $ProductId = $JsonParameters.PSobject.Properties["product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_product_id"))) { #optional property not found
            $OrderProductId = $null
        } else {
            $OrderProductId = $JsonParameters.PSobject.Properties["order_product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "price"))) { #optional property not found
            $Price = $null
        } else {
            $Price = $JsonParameters.PSobject.Properties["price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "price_inc_tax"))) { #optional property not found
            $PriceIncTax = $null
        } else {
            $PriceIncTax = $JsonParameters.PSobject.Properties["price_inc_tax"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "quantity"))) { #optional property not found
            $Quantity = $null
        } else {
            $Quantity = $JsonParameters.PSobject.Properties["quantity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "discount_amount"))) { #optional property not found
            $DiscountAmount = $null
        } else {
            $DiscountAmount = $JsonParameters.PSobject.Properties["discount_amount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "total_price"))) { #optional property not found
            $TotalPrice = $null
        } else {
            $TotalPrice = $JsonParameters.PSobject.Properties["total_price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tax_percent"))) { #optional property not found
            $TaxPercent = $null
        } else {
            $TaxPercent = $JsonParameters.PSobject.Properties["tax_percent"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tax_value"))) { #optional property not found
            $TaxValue = $null
        } else {
            $TaxValue = $JsonParameters.PSobject.Properties["tax_value"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tax_value_after_discount"))) { #optional property not found
            $TaxValueAfterDiscount = $null
        } else {
            $TaxValueAfterDiscount = $JsonParameters.PSobject.Properties["tax_value_after_discount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "options"))) { #optional property not found
            $Options = $null
        } else {
            $Options = $JsonParameters.PSobject.Properties["options"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "variant_id"))) { #optional property not found
            $VariantId = $null
        } else {
            $VariantId = $JsonParameters.PSobject.Properties["variant_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "weight_unit"))) { #optional property not found
            $WeightUnit = $null
        } else {
            $WeightUnit = $JsonParameters.PSobject.Properties["weight_unit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "weight"))) { #optional property not found
            $Weight = $null
        } else {
            $Weight = $JsonParameters.PSobject.Properties["weight"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "barcode"))) { #optional property not found
            $Barcode = $null
        } else {
            $Barcode = $JsonParameters.PSobject.Properties["barcode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parent_order_product_id"))) { #optional property not found
            $ParentOrderProductId = $null
        } else {
            $ParentOrderProductId = $JsonParameters.PSobject.Properties["parent_order_product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "order_product_id" = ${OrderProductId}
            "model" = ${Model}
            "name" = ${Name}
            "price" = ${Price}
            "price_inc_tax" = ${PriceIncTax}
            "quantity" = ${Quantity}
            "discount_amount" = ${DiscountAmount}
            "total_price" = ${TotalPrice}
            "tax_percent" = ${TaxPercent}
            "tax_value" = ${TaxValue}
            "tax_value_after_discount" = ${TaxValueAfterDiscount}
            "options" = ${Options}
            "variant_id" = ${VariantId}
            "weight_unit" = ${WeightUnit}
            "weight" = ${Weight}
            "barcode" = ${Barcode}
            "parent_order_product_id" = ${ParentOrderProductId}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

