#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Code
No description available.
.PARAMETER Name
No description available.
.PARAMETER Price
No description available.
.PARAMETER PriceIncTax
No description available.
.PARAMETER Tax
No description available.
.PARAMETER TaxRate
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

OrderCalculateShippingRate<PSCustomObject>
#>

function Initialize-OrderCalculateShippingRate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Code},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Price},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${PriceIncTax},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Tax},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${TaxRate},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderCalculateShippingRate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "code" = ${Code}
            "name" = ${Name}
            "price" = ${Price}
            "price_inc_tax" = ${PriceIncTax}
            "tax" = ${Tax}
            "tax_rate" = ${TaxRate}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderCalculateShippingRate<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderCalculateShippingRate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderCalculateShippingRate<PSCustomObject>
#>
function ConvertFrom-JsonToOrderCalculateShippingRate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderCalculateShippingRate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderCalculateShippingRate
        $AllProperties = ("code", "name", "price", "price_inc_tax", "tax", "tax_rate", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "code"))) { #optional property not found
            $Code = $null
        } else {
            $Code = $JsonParameters.PSobject.Properties["code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "price"))) { #optional property not found
            $Price = $null
        } else {
            $Price = $JsonParameters.PSobject.Properties["price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "price_inc_tax"))) { #optional property not found
            $PriceIncTax = $null
        } else {
            $PriceIncTax = $JsonParameters.PSobject.Properties["price_inc_tax"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tax"))) { #optional property not found
            $Tax = $null
        } else {
            $Tax = $JsonParameters.PSobject.Properties["tax"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tax_rate"))) { #optional property not found
            $TaxRate = $null
        } else {
            $TaxRate = $JsonParameters.PSobject.Properties["tax_rate"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "code" = ${Code}
            "name" = ${Name}
            "price" = ${Price}
            "price_inc_tax" = ${PriceIncTax}
            "tax" = ${Tax}
            "tax_rate" = ${TaxRate}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

