#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DeletedItems
No description available.
.OUTPUTS

OrderShipmentDelete200ResponseResult<PSCustomObject>
#>

function Initialize-OrderShipmentDelete200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${DeletedItems}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderShipmentDelete200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "deleted_items" = ${DeletedItems}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderShipmentDelete200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderShipmentDelete200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderShipmentDelete200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToOrderShipmentDelete200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderShipmentDelete200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderShipmentDelete200ResponseResult
        $AllProperties = ("deleted_items")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "deleted_items"))) { #optional property not found
            $DeletedItems = $null
        } else {
            $DeletedItems = $JsonParameters.PSobject.Properties["deleted_items"].value
        }

        $PSO = [PSCustomObject]@{
            "deleted_items" = ${DeletedItems}
        }

        return $PSO
    }

}

