#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER OrderFulfillmentStatuses
No description available.
.OUTPUTS

OrderFulfillmentStatusList200ResponseResult<PSCustomObject>
#>

function Initialize-OrderFulfillmentStatusList200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${OrderFulfillmentStatuses}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderFulfillmentStatusList200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "order_fulfillment_statuses" = ${OrderFulfillmentStatuses}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderFulfillmentStatusList200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderFulfillmentStatusList200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderFulfillmentStatusList200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToOrderFulfillmentStatusList200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderFulfillmentStatusList200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderFulfillmentStatusList200ResponseResult
        $AllProperties = ("order_fulfillment_statuses")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_fulfillment_statuses"))) { #optional property not found
            $OrderFulfillmentStatuses = $null
        } else {
            $OrderFulfillmentStatuses = $JsonParameters.PSobject.Properties["order_fulfillment_statuses"].value
        }

        $PSO = [PSCustomObject]@{
            "order_fulfillment_statuses" = ${OrderFulfillmentStatuses}
        }

        return $PSO
    }

}

