#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER OrderItemId
Defines orders specified by order item id
.PARAMETER OrderItemModel
Defines orders specified by order item model
.PARAMETER OrderItemQuantity
Defines orders specified by order item quantity
.PARAMETER OrderItemWeight
Defines orders specified by order item weight
.PARAMETER OrderItemVariantId
Ordered product variant. Where x is order item ID
.PARAMETER OrderItemOption
No description available.
.OUTPUTS

OrderPreestimateShippingListOrderItemInner<PSCustomObject>
#>

function Initialize-OrderPreestimateShippingListOrderItemInner {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderItemId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderItemModel},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${OrderItemQuantity},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${OrderItemWeight},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderItemVariantId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${OrderItemOption}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => OrderPreestimateShippingListOrderItemInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $OrderItemId) {
            throw "invalid value for 'OrderItemId', 'OrderItemId' cannot be null."
        }

        if ($null -eq $OrderItemQuantity) {
            throw "invalid value for 'OrderItemQuantity', 'OrderItemQuantity' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "order_item_id" = ${OrderItemId}
            "order_item_model" = ${OrderItemModel}
            "order_item_quantity" = ${OrderItemQuantity}
            "order_item_weight" = ${OrderItemWeight}
            "order_item_variant_id" = ${OrderItemVariantId}
            "order_item_option" = ${OrderItemOption}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OrderPreestimateShippingListOrderItemInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to OrderPreestimateShippingListOrderItemInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OrderPreestimateShippingListOrderItemInner<PSCustomObject>
#>
function ConvertFrom-JsonToOrderPreestimateShippingListOrderItemInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => OrderPreestimateShippingListOrderItemInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OrderPreestimateShippingListOrderItemInner
        $AllProperties = ("order_item_id", "order_item_model", "order_item_quantity", "order_item_weight", "order_item_variant_id", "order_item_option")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'order_item_id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'order_item_id' missing."
        } else {
            $OrderItemId = $JsonParameters.PSobject.Properties["order_item_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_quantity"))) {
            throw "Error! JSON cannot be serialized due to the required property 'order_item_quantity' missing."
        } else {
            $OrderItemQuantity = $JsonParameters.PSobject.Properties["order_item_quantity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_model"))) { #optional property not found
            $OrderItemModel = $null
        } else {
            $OrderItemModel = $JsonParameters.PSobject.Properties["order_item_model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_weight"))) { #optional property not found
            $OrderItemWeight = $null
        } else {
            $OrderItemWeight = $JsonParameters.PSobject.Properties["order_item_weight"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_variant_id"))) { #optional property not found
            $OrderItemVariantId = $null
        } else {
            $OrderItemVariantId = $JsonParameters.PSobject.Properties["order_item_variant_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_item_option"))) { #optional property not found
            $OrderItemOption = $null
        } else {
            $OrderItemOption = $JsonParameters.PSobject.Properties["order_item_option"].value
        }

        $PSO = [PSCustomObject]@{
            "order_item_id" = ${OrderItemId}
            "order_item_model" = ${OrderItemModel}
            "order_item_quantity" = ${OrderItemQuantity}
            "order_item_weight" = ${OrderItemWeight}
            "order_item_variant_id" = ${OrderItemVariantId}
            "order_item_option" = ${OrderItemOption}
        }

        return $PSO
    }

}

