#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Location
No description available.
.PARAMETER Type
No description available.
.PARAMETER SessionDuration
No description available.
.PARAMETER SessionGap
No description available.
.PARAMETER SessionsCount
No description available.
.PARAMETER TimeStrictValue
No description available.
.PARAMETER TimeStrictType
No description available.
.PARAMETER Availabilities
No description available.
.PARAMETER Overrides
No description available.
.OUTPUTS

ProductAddSpecificsInnerBookingDetails<PSCustomObject>
#>

function Initialize-ProductAddSpecificsInnerBookingDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Location},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("date", "date_time")]
        [String]
        ${Type},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SessionDuration},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SessionGap},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${SessionsCount},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${TimeStrictValue},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("days", "hours", "minutes")]
        [String]
        ${TimeStrictType} = "days",
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Availabilities},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Overrides}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductAddSpecificsInnerBookingDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Location) {
            throw "invalid value for 'Location', 'Location' cannot be null."
        }

        if ($Location.length -lt 1) {
            throw "invalid value for 'Location', the character length must be great than or equal to 1."
        }

        if ($null -eq $Type) {
            throw "invalid value for 'Type', 'Type' cannot be null."
        }

        if ($null -eq $SessionsCount) {
            throw "invalid value for 'SessionsCount', 'SessionsCount' cannot be null."
        }

        if ($null -eq $TimeStrictValue) {
            throw "invalid value for 'TimeStrictValue', 'TimeStrictValue' cannot be null."
        }

        if ($null -eq $TimeStrictType) {
            throw "invalid value for 'TimeStrictType', 'TimeStrictType' cannot be null."
        }

        if ($null -eq $Availabilities) {
            throw "invalid value for 'Availabilities', 'Availabilities' cannot be null."
        }

        if ($Availabilities.length -lt 1) {
            throw "invalid value for 'Availabilities', number of items must be greater than or equal to 1."
        }

        if (!$Overrides -and $Overrides.length -lt 1) {
            throw "invalid value for 'Overrides', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "location" = ${Location}
            "type" = ${Type}
            "session_duration" = ${SessionDuration}
            "session_gap" = ${SessionGap}
            "sessions_count" = ${SessionsCount}
            "time_strict_value" = ${TimeStrictValue}
            "time_strict_type" = ${TimeStrictType}
            "availabilities" = ${Availabilities}
            "overrides" = ${Overrides}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductAddSpecificsInnerBookingDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductAddSpecificsInnerBookingDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductAddSpecificsInnerBookingDetails<PSCustomObject>
#>
function ConvertFrom-JsonToProductAddSpecificsInnerBookingDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductAddSpecificsInnerBookingDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductAddSpecificsInnerBookingDetails
        $AllProperties = ("location", "type", "session_duration", "session_gap", "sessions_count", "time_strict_value", "time_strict_type", "availabilities", "overrides")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'location' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "location"))) {
            throw "Error! JSON cannot be serialized due to the required property 'location' missing."
        } else {
            $Location = $JsonParameters.PSobject.Properties["location"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'type' missing."
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sessions_count"))) {
            throw "Error! JSON cannot be serialized due to the required property 'sessions_count' missing."
        } else {
            $SessionsCount = $JsonParameters.PSobject.Properties["sessions_count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time_strict_value"))) {
            throw "Error! JSON cannot be serialized due to the required property 'time_strict_value' missing."
        } else {
            $TimeStrictValue = $JsonParameters.PSobject.Properties["time_strict_value"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time_strict_type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'time_strict_type' missing."
        } else {
            $TimeStrictType = $JsonParameters.PSobject.Properties["time_strict_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "availabilities"))) {
            throw "Error! JSON cannot be serialized due to the required property 'availabilities' missing."
        } else {
            $Availabilities = $JsonParameters.PSobject.Properties["availabilities"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "session_duration"))) { #optional property not found
            $SessionDuration = $null
        } else {
            $SessionDuration = $JsonParameters.PSobject.Properties["session_duration"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "session_gap"))) { #optional property not found
            $SessionGap = $null
        } else {
            $SessionGap = $JsonParameters.PSobject.Properties["session_gap"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "overrides"))) { #optional property not found
            $Overrides = $null
        } else {
            $Overrides = $JsonParameters.PSobject.Properties["overrides"].value
        }

        $PSO = [PSCustomObject]@{
            "location" = ${Location}
            "type" = ${Type}
            "session_duration" = ${SessionDuration}
            "session_gap" = ${SessionGap}
            "sessions_count" = ${SessionsCount}
            "time_strict_value" = ${TimeStrictValue}
            "time_strict_type" = ${TimeStrictType}
            "availabilities" = ${Availabilities}
            "overrides" = ${Overrides}
        }

        return $PSO
    }

}

