#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CurrencyId
No description available.
.OUTPUTS

ProductCurrencyAdd200ResponseResult<PSCustomObject>
#>

function Initialize-ProductCurrencyAdd200ResponseResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CurrencyId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductCurrencyAdd200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "currency_id" = ${CurrencyId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductCurrencyAdd200ResponseResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductCurrencyAdd200ResponseResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductCurrencyAdd200ResponseResult<PSCustomObject>
#>
function ConvertFrom-JsonToProductCurrencyAdd200ResponseResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductCurrencyAdd200ResponseResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductCurrencyAdd200ResponseResult
        $AllProperties = ("currency_id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "currency_id"))) { #optional property not found
            $CurrencyId = $null
        } else {
            $CurrencyId = $JsonParameters.PSobject.Properties["currency_id"].value
        }

        $PSO = [PSCustomObject]@{
            "currency_id" = ${CurrencyId}
        }

        return $PSO
    }

}

