#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The price at which Best Offers are automatically accepted.<hr><div style=""font-style:normal"">Param structure:<div style=""margin-left: 2%;""><code style=""padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;"">best_offer[<b>minimum_offer_price</b>] = decimal</br>best_offer[<b>auto_accept_price</b>] = decimal</br></code></div></div>

.PARAMETER MinimumOfferPrice
No description available.
.PARAMETER AutoAcceptPrice
No description available.
.OUTPUTS

ProductAddBestOffer<PSCustomObject>
#>

function Initialize-ProductAddBestOffer {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${MinimumOfferPrice},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${AutoAcceptPrice}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductAddBestOffer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "minimum_offer_price" = ${MinimumOfferPrice}
            "auto_accept_price" = ${AutoAcceptPrice}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductAddBestOffer<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductAddBestOffer<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductAddBestOffer<PSCustomObject>
#>
function ConvertFrom-JsonToProductAddBestOffer {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductAddBestOffer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductAddBestOffer
        $AllProperties = ("minimum_offer_price", "auto_accept_price")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "minimum_offer_price"))) { #optional property not found
            $MinimumOfferPrice = $null
        } else {
            $MinimumOfferPrice = $JsonParameters.PSobject.Properties["minimum_offer_price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "auto_accept_price"))) { #optional property not found
            $AutoAcceptPrice = $null
        } else {
            $AutoAcceptPrice = $JsonParameters.PSobject.Properties["auto_accept_price"].value
        }

        $PSO = [PSCustomObject]@{
            "minimum_offer_price" = ${MinimumOfferPrice}
            "auto_accept_price" = ${AutoAcceptPrice}
        }

        return $PSO
    }

}

