#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Payload
Contains an array of product deletion requests, each including the product ID.
.OUTPUTS

ProductDeleteBatch<PSCustomObject>
#>

function Initialize-ProductDeleteBatch {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Payload}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductDeleteBatch' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Payload) {
            throw "invalid value for 'Payload', 'Payload' cannot be null."
        }

        if ($Payload.length -gt 250) {
            throw "invalid value for 'Payload', number of items must be less than or equal to 250."
        }

        if ($Payload.length -lt 1) {
            throw "invalid value for 'Payload', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "payload" = ${Payload}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductDeleteBatch<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductDeleteBatch<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductDeleteBatch<PSCustomObject>
#>
function ConvertFrom-JsonToProductDeleteBatch {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductDeleteBatch' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductDeleteBatch
        $AllProperties = ("payload")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'payload' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "payload"))) {
            throw "Error! JSON cannot be serialized due to the required property 'payload' missing."
        } else {
            $Payload = $JsonParameters.PSobject.Properties["payload"].value
        }

        $PSO = [PSCustomObject]@{
            "payload" = ${Payload}
        }

        return $PSO
    }

}

