#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Quantity
No description available.
.OUTPUTS

ProductAddSpecificsInnerGroupProductsDetailsInner<PSCustomObject>
#>

function Initialize-ProductAddSpecificsInnerGroupProductsDetailsInner {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Quantity}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductAddSpecificsInnerGroupProductsDetailsInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Quantity) {
            throw "invalid value for 'Quantity', 'Quantity' cannot be null."
        }

        if ($Quantity -lt 1) {
          throw "invalid value for 'Quantity', must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "quantity" = ${Quantity}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductAddSpecificsInnerGroupProductsDetailsInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductAddSpecificsInnerGroupProductsDetailsInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductAddSpecificsInnerGroupProductsDetailsInner<PSCustomObject>
#>
function ConvertFrom-JsonToProductAddSpecificsInnerGroupProductsDetailsInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductAddSpecificsInnerGroupProductsDetailsInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductAddSpecificsInnerGroupProductsDetailsInner
        $AllProperties = ("id", "quantity")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "quantity"))) {
            throw "Error! JSON cannot be serialized due to the required property 'quantity' missing."
        } else {
            $Quantity = $JsonParameters.PSobject.Properties["quantity"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "quantity" = ${Quantity}
        }

        return $PSO
    }

}

