#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ChildItemId
No description available.
.PARAMETER ProductId
No description available.
.PARAMETER DefaultQtyInPack
No description available.
.PARAMETER IsQtyInPackFixed
No description available.
.PARAMETER Price
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

ProductGroupItem<PSCustomObject>
#>

function Initialize-ProductGroupItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ChildItemId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DefaultQtyInPack},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsQtyInPackFixed},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${Price},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductGroupItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "child_item_id" = ${ChildItemId}
            "product_id" = ${ProductId}
            "default_qty_in_pack" = ${DefaultQtyInPack}
            "is_qty_in_pack_fixed" = ${IsQtyInPackFixed}
            "price" = ${Price}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductGroupItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductGroupItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductGroupItem<PSCustomObject>
#>
function ConvertFrom-JsonToProductGroupItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductGroupItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductGroupItem
        $AllProperties = ("child_item_id", "product_id", "default_qty_in_pack", "is_qty_in_pack_fixed", "price", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "child_item_id"))) { #optional property not found
            $ChildItemId = $null
        } else {
            $ChildItemId = $JsonParameters.PSobject.Properties["child_item_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "product_id"))) { #optional property not found
            $ProductId = $null
        } else {
            $ProductId = $JsonParameters.PSobject.Properties["product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "default_qty_in_pack"))) { #optional property not found
            $DefaultQtyInPack = $null
        } else {
            $DefaultQtyInPack = $JsonParameters.PSobject.Properties["default_qty_in_pack"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "is_qty_in_pack_fixed"))) { #optional property not found
            $IsQtyInPackFixed = $null
        } else {
            $IsQtyInPackFixed = $JsonParameters.PSobject.Properties["is_qty_in_pack_fixed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "price"))) { #optional property not found
            $Price = $null
        } else {
            $Price = $JsonParameters.PSobject.Properties["price"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "child_item_id" = ${ChildItemId}
            "product_id" = ${ProductId}
            "default_qty_in_pack" = ${DefaultQtyInPack}
            "is_qty_in_pack_fixed" = ${IsQtyInPackFixed}
            "price" = ${Price}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

