#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ProductId
Defines product id where the image should be added
.PARAMETER ImageName
Defines image's name
.PARAMETER Type
Defines image's types that are specified by comma-separated list
.PARAMETER Url
Defines URL of the image that has to be added
.PARAMETER Label
Defines alternative text that has to be attached to the picture
.PARAMETER Mime
Mime type of image http://en.wikipedia.org/wiki/Internet_media_type.
.PARAMETER Position
Defines image’s position in the list
.PARAMETER Content
Content(body) encoded in base64 of image file
.PARAMETER ProductVariantId
Defines product's variants specified by variant id
.PARAMETER VariantIds
Defines product's variants ids
.PARAMETER OptionValueIds
Defines product's option values ids
.PARAMETER StoreId
Store Id
.PARAMETER LangId
Add product image on specified language id
.PARAMETER UseLatestApiVersion
Use the latest platform API version
.OUTPUTS

ProductImageAdd<PSCustomObject>
#>

function Initialize-ProductImageAdd {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImageName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("small", "base", "additional", "thumbnail")]
        [String]
        ${Type},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Label},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Mime},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Position} = 0,
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Content},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductVariantId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VariantIds},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OptionValueIds},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${StoreId},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LangId},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${UseLatestApiVersion} = $false
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ProductImageAdd' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ImageName) {
            throw "invalid value for 'ImageName', 'ImageName' cannot be null."
        }

        if ($null -eq $Type) {
            throw "invalid value for 'Type', 'Type' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "image_name" = ${ImageName}
            "type" = ${Type}
            "url" = ${Url}
            "label" = ${Label}
            "mime" = ${Mime}
            "position" = ${Position}
            "content" = ${Content}
            "product_variant_id" = ${ProductVariantId}
            "variant_ids" = ${VariantIds}
            "option_value_ids" = ${OptionValueIds}
            "store_id" = ${StoreId}
            "lang_id" = ${LangId}
            "use_latest_api_version" = ${UseLatestApiVersion}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ProductImageAdd<PSCustomObject>

.DESCRIPTION

Convert from JSON to ProductImageAdd<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ProductImageAdd<PSCustomObject>
#>
function ConvertFrom-JsonToProductImageAdd {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ProductImageAdd' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ProductImageAdd
        $AllProperties = ("product_id", "image_name", "type", "url", "label", "mime", "position", "content", "product_variant_id", "variant_ids", "option_value_ids", "store_id", "lang_id", "use_latest_api_version")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'image_name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "image_name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'image_name' missing."
        } else {
            $ImageName = $JsonParameters.PSobject.Properties["image_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'type' missing."
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "product_id"))) { #optional property not found
            $ProductId = $null
        } else {
            $ProductId = $JsonParameters.PSobject.Properties["product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "label"))) { #optional property not found
            $Label = $null
        } else {
            $Label = $JsonParameters.PSobject.Properties["label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mime"))) { #optional property not found
            $Mime = $null
        } else {
            $Mime = $JsonParameters.PSobject.Properties["mime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "position"))) { #optional property not found
            $Position = $null
        } else {
            $Position = $JsonParameters.PSobject.Properties["position"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "content"))) { #optional property not found
            $Content = $null
        } else {
            $Content = $JsonParameters.PSobject.Properties["content"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "product_variant_id"))) { #optional property not found
            $ProductVariantId = $null
        } else {
            $ProductVariantId = $JsonParameters.PSobject.Properties["product_variant_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "variant_ids"))) { #optional property not found
            $VariantIds = $null
        } else {
            $VariantIds = $JsonParameters.PSobject.Properties["variant_ids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "option_value_ids"))) { #optional property not found
            $OptionValueIds = $null
        } else {
            $OptionValueIds = $JsonParameters.PSobject.Properties["option_value_ids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "store_id"))) { #optional property not found
            $StoreId = $null
        } else {
            $StoreId = $JsonParameters.PSobject.Properties["store_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lang_id"))) { #optional property not found
            $LangId = $null
        } else {
            $LangId = $JsonParameters.PSobject.Properties["lang_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "use_latest_api_version"))) { #optional property not found
            $UseLatestApiVersion = $null
        } else {
            $UseLatestApiVersion = $JsonParameters.PSobject.Properties["use_latest_api_version"].value
        }

        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "image_name" = ${ImageName}
            "type" = ${Type}
            "url" = ${Url}
            "label" = ${Label}
            "mime" = ${Mime}
            "position" = ${Position}
            "content" = ${Content}
            "product_variant_id" = ${ProductVariantId}
            "variant_ids" = ${VariantIds}
            "option_value_ids" = ${OptionValueIds}
            "store_id" = ${StoreId}
            "lang_id" = ${LangId}
            "use_latest_api_version" = ${UseLatestApiVersion}
        }

        return $PSO
    }

}

