#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CatalogPriceRulesCount
No description available.
.PARAMETER CatalogPriceRules
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

ResponseCartCatalogPriceRulesListResult<PSCustomObject>
#>

function Initialize-ResponseCartCatalogPriceRulesListResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CatalogPriceRulesCount},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${CatalogPriceRules},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ResponseCartCatalogPriceRulesListResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "catalog_price_rules_count" = ${CatalogPriceRulesCount}
            "catalog_price_rules" = ${CatalogPriceRules}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ResponseCartCatalogPriceRulesListResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to ResponseCartCatalogPriceRulesListResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ResponseCartCatalogPriceRulesListResult<PSCustomObject>
#>
function ConvertFrom-JsonToResponseCartCatalogPriceRulesListResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ResponseCartCatalogPriceRulesListResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ResponseCartCatalogPriceRulesListResult
        $AllProperties = ("catalog_price_rules_count", "catalog_price_rules", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "catalog_price_rules_count"))) { #optional property not found
            $CatalogPriceRulesCount = $null
        } else {
            $CatalogPriceRulesCount = $JsonParameters.PSobject.Properties["catalog_price_rules_count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "catalog_price_rules"))) { #optional property not found
            $CatalogPriceRules = $null
        } else {
            $CatalogPriceRules = $JsonParameters.PSobject.Properties["catalog_price_rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "catalog_price_rules_count" = ${CatalogPriceRulesCount}
            "catalog_price_rules" = ${CatalogPriceRules}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

