#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CustomersCount
No description available.
.PARAMETER Customer
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

ResponseCustomerListResult<PSCustomObject>
#>

function Initialize-ResponseCustomerListResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CustomersCount},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Customer},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ResponseCustomerListResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "customers_count" = ${CustomersCount}
            "customer" = ${Customer}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ResponseCustomerListResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to ResponseCustomerListResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ResponseCustomerListResult<PSCustomObject>
#>
function ConvertFrom-JsonToResponseCustomerListResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ResponseCustomerListResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ResponseCustomerListResult
        $AllProperties = ("customers_count", "customer", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customers_count"))) { #optional property not found
            $CustomersCount = $null
        } else {
            $CustomersCount = $JsonParameters.PSobject.Properties["customers_count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customer"))) { #optional property not found
            $Customer = $null
        } else {
            $Customer = $JsonParameters.PSobject.Properties["customer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "customers_count" = ${CustomersCount}
            "customer" = ${Customer}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

