#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER MarketplaceProductsCount
No description available.
.PARAMETER MarketplaceProduct
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

ResponseMarketplaceProductFindResult<PSCustomObject>
#>

function Initialize-ResponseMarketplaceProductFindResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MarketplaceProductsCount},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${MarketplaceProduct},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ResponseMarketplaceProductFindResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "marketplace_products_count" = ${MarketplaceProductsCount}
            "marketplace_product" = ${MarketplaceProduct}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ResponseMarketplaceProductFindResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to ResponseMarketplaceProductFindResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ResponseMarketplaceProductFindResult<PSCustomObject>
#>
function ConvertFrom-JsonToResponseMarketplaceProductFindResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ResponseMarketplaceProductFindResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ResponseMarketplaceProductFindResult
        $AllProperties = ("marketplace_products_count", "marketplace_product", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "marketplace_products_count"))) { #optional property not found
            $MarketplaceProductsCount = $null
        } else {
            $MarketplaceProductsCount = $JsonParameters.PSobject.Properties["marketplace_products_count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "marketplace_product"))) { #optional property not found
            $MarketplaceProduct = $null
        } else {
            $MarketplaceProduct = $JsonParameters.PSobject.Properties["marketplace_product"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "marketplace_products_count" = ${MarketplaceProductsCount}
            "marketplace_product" = ${MarketplaceProduct}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

