#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ProductId
No description available.
.PARAMETER OrderProductId
No description available.
.PARAMETER Sku
No description available.
.PARAMETER Name
No description available.
.PARAMETER Quantity
No description available.
.PARAMETER Reason
No description available.
.PARAMETER Action
No description available.
.PARAMETER Condition
No description available.
.PARAMETER CustomerComment
No description available.
.PARAMETER AdditionalFields
No description available.
.PARAMETER CustomFields
No description available.
.OUTPUTS

ReturnOrderProduct<PSCustomObject>
#>

function Initialize-ReturnOrderProduct {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProductId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OrderProductId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Sku},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Quantity},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Reason},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Action},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Condition},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CustomerComment},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalFields},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ReturnOrderProduct' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "order_product_id" = ${OrderProductId}
            "sku" = ${Sku}
            "name" = ${Name}
            "quantity" = ${Quantity}
            "reason" = ${Reason}
            "action" = ${Action}
            "condition" = ${Condition}
            "customer_comment" = ${CustomerComment}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ReturnOrderProduct<PSCustomObject>

.DESCRIPTION

Convert from JSON to ReturnOrderProduct<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ReturnOrderProduct<PSCustomObject>
#>
function ConvertFrom-JsonToReturnOrderProduct {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ReturnOrderProduct' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ReturnOrderProduct
        $AllProperties = ("product_id", "order_product_id", "sku", "name", "quantity", "reason", "action", "condition", "customer_comment", "additional_fields", "custom_fields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "product_id"))) { #optional property not found
            $ProductId = $null
        } else {
            $ProductId = $JsonParameters.PSobject.Properties["product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "order_product_id"))) { #optional property not found
            $OrderProductId = $null
        } else {
            $OrderProductId = $JsonParameters.PSobject.Properties["order_product_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sku"))) { #optional property not found
            $Sku = $null
        } else {
            $Sku = $JsonParameters.PSobject.Properties["sku"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "quantity"))) { #optional property not found
            $Quantity = $null
        } else {
            $Quantity = $JsonParameters.PSobject.Properties["quantity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reason"))) { #optional property not found
            $Reason = $null
        } else {
            $Reason = $JsonParameters.PSobject.Properties["reason"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "action"))) { #optional property not found
            $Action = $null
        } else {
            $Action = $JsonParameters.PSobject.Properties["action"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "condition"))) { #optional property not found
            $Condition = $null
        } else {
            $Condition = $JsonParameters.PSobject.Properties["condition"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customer_comment"))) { #optional property not found
            $CustomerComment = $null
        } else {
            $CustomerComment = $JsonParameters.PSobject.Properties["customer_comment"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additional_fields"))) { #optional property not found
            $AdditionalFields = $null
        } else {
            $AdditionalFields = $JsonParameters.PSobject.Properties["additional_fields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "custom_fields"))) { #optional property not found
            $CustomFields = $null
        } else {
            $CustomFields = $JsonParameters.PSobject.Properties["custom_fields"].value
        }

        $PSO = [PSCustomObject]@{
            "product_id" = ${ProductId}
            "order_product_id" = ${OrderProductId}
            "sku" = ${Sku}
            "name" = ${Name}
            "quantity" = ${Quantity}
            "reason" = ${Reason}
            "action" = ${Action}
            "condition" = ${Condition}
            "customer_comment" = ${CustomerComment}
            "additional_fields" = ${AdditionalFields}
            "custom_fields" = ${CustomFields}
        }

        return $PSO
    }

}

