#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'BasketApi' {
    Context 'Invoke-BasketInfo' {
        It 'Test Invoke-BasketInfo' {
            #$TestResult = Invoke-BasketInfo -Id "TEST_VALUE" -StoreId "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-BasketItemAdd' {
        It 'Test Invoke-BasketItemAdd' {
            #$TestResult = Invoke-BasketItemAdd -CustomerId "TEST_VALUE" -ProductId "TEST_VALUE" -VariantId "TEST_VALUE" -Quantity "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-BasketLiveShippingServiceCreate' {
        It 'Test Invoke-BasketLiveShippingServiceCreate' {
            #$TestResult = Invoke-BasketLiveShippingServiceCreate -Name "TEST_VALUE" -Callback "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-BasketLiveShippingServiceDelete' {
        It 'Test Invoke-BasketLiveShippingServiceDelete' {
            #$TestResult = Invoke-BasketLiveShippingServiceDelete -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-BasketLiveShippingServiceList' {
        It 'Test Invoke-BasketLiveShippingServiceList' {
            #$TestResult = Invoke-BasketLiveShippingServiceList -Start "TEST_VALUE" -Count "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
