#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CartApi' {
    Context 'Invoke-CartCatalogPriceRulesCount' {
        It 'Test Invoke-CartCatalogPriceRulesCount' {
            #$TestResult = Invoke-CartCatalogPriceRulesCount
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCatalogPriceRulesList' {
        It 'Test Invoke-CartCatalogPriceRulesList' {
            #$TestResult = Invoke-CartCatalogPriceRulesList -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -Ids "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCouponAdd' {
        It 'Test Invoke-CartCouponAdd' {
            #$TestResult = Invoke-CartCouponAdd -CartCouponAdd "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCouponConditionAdd' {
        It 'Test Invoke-CartCouponConditionAdd' {
            #$TestResult = Invoke-CartCouponConditionAdd -CouponId "TEST_VALUE" -Entity "TEST_VALUE" -Key "TEST_VALUE" -Operator "TEST_VALUE" -Value "TEST_VALUE" -Target "TEST_VALUE" -IncludeTax "TEST_VALUE" -IncludeShipping "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCouponCount' {
        It 'Test Invoke-CartCouponCount' {
            #$TestResult = Invoke-CartCouponCount -StoreId "TEST_VALUE" -Avail "TEST_VALUE" -DateStartFrom "TEST_VALUE" -DateStartTo "TEST_VALUE" -DateEndFrom "TEST_VALUE" -DateEndTo "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCouponDelete' {
        It 'Test Invoke-CartCouponDelete' {
            #$TestResult = Invoke-CartCouponDelete -Id "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartCouponList' {
        It 'Test Invoke-CartCouponList' {
            #$TestResult = Invoke-CartCouponList -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -CouponsIds "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -Avail "TEST_VALUE" -Status "TEST_VALUE" -DateStartFrom "TEST_VALUE" -DateStartTo "TEST_VALUE" -DateEndFrom "TEST_VALUE" -DateEndTo "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartDelete' {
        It 'Test Invoke-CartDelete' {
            #$TestResult = Invoke-CartDelete -DeleteBridge "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartGiftcardAdd' {
        It 'Test Invoke-CartGiftcardAdd' {
            #$TestResult = Invoke-CartGiftcardAdd -Amount "TEST_VALUE" -Code "TEST_VALUE" -OwnerEmail "TEST_VALUE" -RecipientEmail "TEST_VALUE" -RecipientName "TEST_VALUE" -OwnerName "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartGiftcardCount' {
        It 'Test Invoke-CartGiftcardCount' {
            #$TestResult = Invoke-CartGiftcardCount -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartGiftcardDelete' {
        It 'Test Invoke-CartGiftcardDelete' {
            #$TestResult = Invoke-CartGiftcardDelete -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartGiftcardList' {
        It 'Test Invoke-CartGiftcardList' {
            #$TestResult = Invoke-CartGiftcardList -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -StoreId "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartInfo' {
        It 'Test Invoke-CartInfo' {
            #$TestResult = Invoke-CartInfo -StoreId "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartMetaDataList' {
        It 'Test Invoke-CartMetaDataList' {
            #$TestResult = Invoke-CartMetaDataList -EntityId "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -Entity "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -Key "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartMetaDataSet' {
        It 'Test Invoke-CartMetaDataSet' {
            #$TestResult = Invoke-CartMetaDataSet -EntityId "TEST_VALUE" -Key "TEST_VALUE" -Value "TEST_VALUE" -Namespace "TEST_VALUE" -Entity "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartMetaDataUnset' {
        It 'Test Invoke-CartMetaDataUnset' {
            #$TestResult = Invoke-CartMetaDataUnset -EntityId "TEST_VALUE" -Key "TEST_VALUE" -Id "TEST_VALUE" -Entity "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartMethods' {
        It 'Test Invoke-CartMethods' {
            #$TestResult = Invoke-CartMethods
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartPluginList' {
        It 'Test Invoke-CartPluginList' {
            #$TestResult = Invoke-CartPluginList -Start "TEST_VALUE" -Count "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartScriptAdd' {
        It 'Test Invoke-CartScriptAdd' {
            #$TestResult = Invoke-CartScriptAdd -Name "TEST_VALUE" -Description "TEST_VALUE" -Html "TEST_VALUE" -Src "TEST_VALUE" -LoadMethod "TEST_VALUE" -Scope "TEST_VALUE" -Events "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartScriptDelete' {
        It 'Test Invoke-CartScriptDelete' {
            #$TestResult = Invoke-CartScriptDelete -Id "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartScriptList' {
        It 'Test Invoke-CartScriptList' {
            #$TestResult = Invoke-CartScriptList -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -ScriptIds "TEST_VALUE" -StoreId "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -ModifiedFrom "TEST_VALUE" -ModifiedTo "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartShippingZonesList' {
        It 'Test Invoke-CartShippingZonesList' {
            #$TestResult = Invoke-CartShippingZonesList -Start "TEST_VALUE" -Count "TEST_VALUE" -StoreId "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CartValidate' {
        It 'Test Invoke-CartValidate' {
            #$TestResult = Invoke-CartValidate -ValidateVersion "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
