#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CategoryApi' {
    Context 'Get-egoryAdd' {
        It 'Test Get-egoryAdd' {
            #$TestResult = Get-egoryAdd -Name "TEST_VALUE" -Description "TEST_VALUE" -ShortDescription "TEST_VALUE" -ParentId "TEST_VALUE" -Avail "TEST_VALUE" -CreatedTime "TEST_VALUE" -ModifiedTime "TEST_VALUE" -SortOrder "TEST_VALUE" -MetaTitle "TEST_VALUE" -MetaDescription "TEST_VALUE" -MetaKeywords "TEST_VALUE" -SeoUrl "TEST_VALUE" -StoreId "TEST_VALUE" -StoresIds "TEST_VALUE" -LangId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryAddBatch' {
        It 'Test Get-egoryAddBatch' {
            #$TestResult = Get-egoryAddBatch -CategoryAddBatch "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryAssign' {
        It 'Test Get-egoryAssign' {
            #$TestResult = Get-egoryAssign -CategoryId "TEST_VALUE" -ProductId "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryCount' {
        It 'Test Get-egoryCount' {
            #$TestResult = Get-egoryCount -ParentId "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -Avail "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -ModifiedFrom "TEST_VALUE" -ModifiedTo "TEST_VALUE" -ProductType "TEST_VALUE" -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -ReportRequestId "TEST_VALUE" -DisableReportCache "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryDelete' {
        It 'Test Get-egoryDelete' {
            #$TestResult = Get-egoryDelete -Id "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryFind' {
        It 'Test Get-egoryFind' {
            #$TestResult = Get-egoryFind -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -FindParams "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryImageAdd' {
        It 'Test Get-egoryImageAdd' {
            #$TestResult = Get-egoryImageAdd -CategoryId "TEST_VALUE" -ImageName "TEST_VALUE" -Url "TEST_VALUE" -Type "TEST_VALUE" -StoreId "TEST_VALUE" -Label "TEST_VALUE" -Mime "TEST_VALUE" -Position "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryImageDelete' {
        It 'Test Get-egoryImageDelete' {
            #$TestResult = Get-egoryImageDelete -CategoryId "TEST_VALUE" -ImageId "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryInfo' {
        It 'Test Get-egoryInfo' {
            #$TestResult = Get-egoryInfo -Id "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -SchemaType "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE" -ReportRequestId "TEST_VALUE" -DisableReportCache "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryList' {
        It 'Test Get-egoryList' {
            #$TestResult = Get-egoryList -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -ParentId "TEST_VALUE" -Avail "TEST_VALUE" -ProductType "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -ModifiedFrom "TEST_VALUE" -ModifiedTo "TEST_VALUE" -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -ResponseFields "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE" -ReportRequestId "TEST_VALUE" -DisableReportCache "TEST_VALUE" -DisableCache "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryUnassign' {
        It 'Test Get-egoryUnassign' {
            #$TestResult = Get-egoryUnassign -CategoryId "TEST_VALUE" -ProductId "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-egoryUpdate' {
        It 'Test Get-egoryUpdate' {
            #$TestResult = Get-egoryUpdate -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -ShortDescription "TEST_VALUE" -ParentId "TEST_VALUE" -Avail "TEST_VALUE" -SortOrder "TEST_VALUE" -ModifiedTime "TEST_VALUE" -MetaTitle "TEST_VALUE" -MetaDescription "TEST_VALUE" -MetaKeywords "TEST_VALUE" -SeoUrl "TEST_VALUE" -StoreId "TEST_VALUE" -StoresIds "TEST_VALUE" -LangId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
