#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CustomerApi' {
    Context 'Invoke-CustomerAdd' {
        It 'Test Invoke-CustomerAdd' {
            #$TestResult = Invoke-CustomerAdd -CustomerAdd "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerAddressAdd' {
        It 'Test Invoke-CustomerAddressAdd' {
            #$TestResult = Invoke-CustomerAddressAdd -CustomerAddressAdd "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerAttributeList' {
        It 'Test Invoke-CustomerAttributeList' {
            #$TestResult = Invoke-CustomerAttributeList -CustomerId "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE" -ResponseFields "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerCount' {
        It 'Test Invoke-CustomerCount' {
            #$TestResult = Invoke-CustomerCount -GroupId "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -ModifiedFrom "TEST_VALUE" -ModifiedTo "TEST_VALUE" -StoreId "TEST_VALUE" -CustomerListId "TEST_VALUE" -Avail "TEST_VALUE" -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -Ids "TEST_VALUE" -SinceId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerDelete' {
        It 'Test Invoke-CustomerDelete' {
            #$TestResult = Invoke-CustomerDelete -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerFind' {
        It 'Test Invoke-CustomerFind' {
            #$TestResult = Invoke-CustomerFind -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -FindParams "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerGroupAdd' {
        It 'Test Invoke-CustomerGroupAdd' {
            #$TestResult = Invoke-CustomerGroupAdd -Name "TEST_VALUE" -StoreId "TEST_VALUE" -StoresIds "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerGroupList' {
        It 'Test Invoke-CustomerGroupList' {
            #$TestResult = Invoke-CustomerGroupList -DisableCache "TEST_VALUE" -PageCursor "TEST_VALUE" -Start "TEST_VALUE" -Count "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -GroupIds "TEST_VALUE" -Params "TEST_VALUE" -Exclude "TEST_VALUE" -ResponseFields "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerInfo' {
        It 'Test Invoke-CustomerInfo' {
            #$TestResult = Invoke-CustomerInfo -Id "TEST_VALUE" -Params "TEST_VALUE" -ResponseFields "TEST_VALUE" -Exclude "TEST_VALUE" -StoreId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerList' {
        It 'Test Invoke-CustomerList' {
            #$TestResult = Invoke-CustomerList -PageCursor "TEST_VALUE" -Start "TEST_VALUE" -Count "TEST_VALUE" -CreatedFrom "TEST_VALUE" -CreatedTo "TEST_VALUE" -ModifiedFrom "TEST_VALUE" -ModifiedTo "TEST_VALUE" -Params "TEST_VALUE" -ResponseFields "TEST_VALUE" -Exclude "TEST_VALUE" -GroupId "TEST_VALUE" -StoreId "TEST_VALUE" -CustomerListId "TEST_VALUE" -Avail "TEST_VALUE" -FindValue "TEST_VALUE" -FindWhere "TEST_VALUE" -SortBy "TEST_VALUE" -SortDirection "TEST_VALUE" -Ids "TEST_VALUE" -SinceId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerUpdate' {
        It 'Test Invoke-CustomerUpdate' {
            #$TestResult = Invoke-CustomerUpdate -CustomerUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-CustomerWishlistList' {
        It 'Test Invoke-CustomerWishlistList' {
            #$TestResult = Invoke-CustomerWishlistList -CustomerId "TEST_VALUE" -Id "TEST_VALUE" -StoreId "TEST_VALUE" -Start "TEST_VALUE" -Count "TEST_VALUE" -PageCursor "TEST_VALUE" -ResponseFields "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
