#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountSupportedPlatforms200ResponseResult' {
    Context 'AccountSupportedPlatforms200ResponseResult' {
        It 'Initialize-AccountSupportedPlatforms200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-AccountSupportedPlatforms200ResponseResult -SupportedPlatforms "TEST_VALUE"
            #$NewObject | Should -BeOfType AccountSupportedPlatforms200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
