#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams' {
    Context 'AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams' {
        It 'Initialize-AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams' {
            # a simple test to create an object
            #$NewObject = Initialize-AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams -Required "TEST_VALUE" -Additional "TEST_VALUE"
            #$NewObject | Should -BeOfType AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams
            #$NewObject.property | Should -Be 0
        }
    }
}
