#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AccountCartAddHybrisWebsitesInner' {
    Context 'AccountCartAddHybrisWebsitesInner' {
        It 'Initialize-AccountCartAddHybrisWebsitesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-AccountCartAddHybrisWebsitesInner -Uid "TEST_VALUE" -Url "TEST_VALUE" -StoreIds "TEST_VALUE"
            #$NewObject | Should -BeOfType AccountCartAddHybrisWebsitesInner
            #$NewObject.property | Should -Be 0
        }
    }
}
