#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'BasketItemOption' {
    Context 'BasketItemOption' {
        It 'Initialize-BasketItemOption' {
            # a simple test to create an object
            #$NewObject = Initialize-BasketItemOption -Id "TEST_VALUE" -ValueId "TEST_VALUE" -Name "TEST_VALUE" -Value "TEST_VALUE" -UsedInCombination "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType BasketItemOption
            #$NewObject.property | Should -Be 0
        }
    }
}
