#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Cart' {
    Context 'Cart' {
        It 'Initialize-Cart' {
            # a simple test to create an object
            #$NewObject = Initialize-Cart -Name "TEST_VALUE" -Url "TEST_VALUE" -Version "TEST_VALUE" -DbPrefix "TEST_VALUE" -StoresInfo "TEST_VALUE" -Warehouses "TEST_VALUE" -ShippingZones "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType Cart
            #$NewObject.property | Should -Be 0
        }
    }
}
