#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CartMetaData' {
    Context 'CartMetaData' {
        It 'Initialize-CartMetaData' {
            # a simple test to create an object
            #$NewObject = Initialize-CartMetaData -Id "TEST_VALUE" -Key "TEST_VALUE" -Value "TEST_VALUE" -Namespace "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType CartMetaData
            #$NewObject.property | Should -Be 0
        }
    }
}
