#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CategoryCount200ResponseResult' {
    Context 'CategoryCount200ResponseResult' {
        It 'Initialize-CategoryCount200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-CategoryCount200ResponseResult -CategoriesCount "TEST_VALUE"
            #$NewObject | Should -BeOfType CategoryCount200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
