#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CouponAction' {
    Context 'CouponAction' {
        It 'Initialize-CouponAction' {
            # a simple test to create an object
            #$NewObject = Initialize-CouponAction -Scope "TEST_VALUE" -ApplyTo "TEST_VALUE" -Amount "TEST_VALUE" -CurrencyCode "TEST_VALUE" -IncludeTax "TEST_VALUE" -Type "TEST_VALUE" -DiscountedQuantity "TEST_VALUE" -DiscountQuantityStep "TEST_VALUE" -LogicOperator "TEST_VALUE" -Conditions "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType CouponAction
            #$NewObject.property | Should -Be 0
        }
    }
}
