#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CouponCode' {
    Context 'CouponCode' {
        It 'Initialize-CouponCode' {
            # a simple test to create an object
            #$NewObject = Initialize-CouponCode -Id "TEST_VALUE" -Code "TEST_VALUE" -UsedTimes "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType CouponCode
            #$NewObject.property | Should -Be 0
        }
    }
}
