#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CustomerAdd200ResponseResult' {
    Context 'CustomerAdd200ResponseResult' {
        It 'Initialize-CustomerAdd200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-CustomerAdd200ResponseResult -CustomerId "TEST_VALUE"
            #$NewObject | Should -BeOfType CustomerAdd200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
