#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'GiftCard' {
    Context 'GiftCard' {
        It 'Initialize-GiftCard' {
            # a simple test to create an object
            #$NewObject = Initialize-GiftCard -Id "TEST_VALUE" -Code "TEST_VALUE" -Name "TEST_VALUE" -Type "TEST_VALUE" -CurrencyCode "TEST_VALUE" -Amount "TEST_VALUE" -InitialAmount "TEST_VALUE" -Status "TEST_VALUE" -CreatedAt "TEST_VALUE" -AvailTo "TEST_VALUE" -FreeProductIds "TEST_VALUE" -Message "TEST_VALUE" -IssuerEmail "TEST_VALUE" -RecipientEmail "TEST_VALUE" -IssuerName "TEST_VALUE" -RecipientName "TEST_VALUE" -UsageHistory "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType GiftCard
            #$NewObject.property | Should -Be 0
        }
    }
}
