#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Media' {
    Context 'Media' {
        It 'Initialize-Media' {
            # a simple test to create an object
            #$NewObject = Initialize-Media -Id "TEST_VALUE" -HttpPath "TEST_VALUE" -FileName "TEST_VALUE" -Type "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType Media
            #$NewObject.property | Should -Be 0
        }
    }
}
