#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ModelResponseTaxClassList' {
    Context 'ModelResponseTaxClassList' {
        It 'Initialize-ModelResponseTaxClassList' {
            # a simple test to create an object
            #$NewObject = Initialize-ModelResponseTaxClassList -ReturnCode "TEST_VALUE" -ReturnMessage "TEST_VALUE" -Pagination "TEST_VALUE" -Result "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ModelResponseTaxClassList
            #$NewObject.property | Should -Be 0
        }
    }
}
