#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ModelResponseCartMetaDataList' {
    Context 'ModelResponseCartMetaDataList' {
        It 'Initialize-ModelResponseCartMetaDataList' {
            # a simple test to create an object
            #$NewObject = Initialize-ModelResponseCartMetaDataList -ReturnCode "TEST_VALUE" -ReturnMessage "TEST_VALUE" -Pagination "TEST_VALUE" -Result "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ModelResponseCartMetaDataList
            #$NewObject.property | Should -Be 0
        }
    }
}
