#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderCalculateSubtotal' {
    Context 'OrderCalculateSubtotal' {
        It 'Initialize-OrderCalculateSubtotal' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderCalculateSubtotal -Value "TEST_VALUE" -Tax "TEST_VALUE" -Discount "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderCalculateSubtotal
            #$NewObject.property | Should -Be 0
        }
    }
}
