#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderAbandoned' {
    Context 'OrderAbandoned' {
        It 'Initialize-OrderAbandoned' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderAbandoned -Id "TEST_VALUE" -Customer "TEST_VALUE" -BasketId "TEST_VALUE" -BasketUrl "TEST_VALUE" -CreatedAt "TEST_VALUE" -ModifiedAt "TEST_VALUE" -Currency "TEST_VALUE" -Totals "TEST_VALUE" -OrderProducts "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderAbandoned
            #$NewObject.property | Should -Be 0
        }
    }
}
