#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderReturnAdd200ResponseResult' {
    Context 'OrderReturnAdd200ResponseResult' {
        It 'Initialize-OrderReturnAdd200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderReturnAdd200ResponseResult -ReturnId "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderReturnAdd200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
