#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderCalculate' {
    Context 'OrderCalculate' {
        It 'Initialize-OrderCalculate' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderCalculate -CustomerEmail "TEST_VALUE" -CurrencyId "TEST_VALUE" -StoreId "TEST_VALUE" -Coupons "TEST_VALUE" -ShippFirstName "TEST_VALUE" -ShippLastName "TEST_VALUE" -ShippAddress1 "TEST_VALUE" -ShippAddress2 "TEST_VALUE" -ShippCity "TEST_VALUE" -ShippPostcode "TEST_VALUE" -ShippState "TEST_VALUE" -ShippCountry "TEST_VALUE" -ShippCompany "TEST_VALUE" -ShippPhone "TEST_VALUE" -BillFirstName "TEST_VALUE" -BillLastName "TEST_VALUE" -BillAddress1 "TEST_VALUE" -BillAddress2 "TEST_VALUE" -BillCity "TEST_VALUE" -BillPostcode "TEST_VALUE" -BillState "TEST_VALUE" -BillCountry "TEST_VALUE" -BillCompany "TEST_VALUE" -BillPhone "TEST_VALUE" -ResponseFields "TEST_VALUE" -OrderItem "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderCalculate
            #$NewObject.property | Should -Be 0
        }
    }
}
