#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'OrderShipmentAddBatchPayloadInnerItemsInner' {
    Context 'OrderShipmentAddBatchPayloadInnerItemsInner' {
        It 'Initialize-OrderShipmentAddBatchPayloadInnerItemsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-OrderShipmentAddBatchPayloadInnerItemsInner -OrderProductId "TEST_VALUE" -Quantity "TEST_VALUE"
            #$NewObject | Should -BeOfType OrderShipmentAddBatchPayloadInnerItemsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
