#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductOption' {
    Context 'ProductOption' {
        It 'Initialize-ProductOption' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductOption -Id "TEST_VALUE" -ProductOptionId "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -SortOrder "TEST_VALUE" -Type "TEST_VALUE" -Required "TEST_VALUE" -Available "TEST_VALUE" -UsedInCombination "TEST_VALUE" -OptionItems "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductOption
            #$NewObject.property | Should -Be 0
        }
    }
}
