#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductOptionAssign200ResponseResult' {
    Context 'ProductOptionAssign200ResponseResult' {
        It 'Initialize-ProductOptionAssign200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductOptionAssign200ResponseResult -ProductOptionId "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductOptionAssign200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
