#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAddManufacturerInfo' {
    Context 'ProductAddManufacturerInfo' {
        It 'Initialize-ProductAddManufacturerInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAddManufacturerInfo -Name "TEST_VALUE" -Address "TEST_VALUE" -Phone "TEST_VALUE" -Email "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAddManufacturerInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
