#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAddBatchPayloadInnerImagesInner' {
    Context 'ProductAddBatchPayloadInnerImagesInner' {
        It 'Initialize-ProductAddBatchPayloadInnerImagesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAddBatchPayloadInnerImagesInner -Type "TEST_VALUE" -Url "TEST_VALUE" -Label "TEST_VALUE" -Name "TEST_VALUE" -Position "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAddBatchPayloadInnerImagesInner
            #$NewObject.property | Should -Be 0
        }
    }
}
