#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductVariantAddBatchPayloadInner' {
    Context 'ProductVariantAddBatchPayloadInner' {
        It 'Initialize-ProductVariantAddBatchPayloadInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductVariantAddBatchPayloadInner -ProductId "TEST_VALUE" -Combination "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -ShortDescription "TEST_VALUE" -Sku "TEST_VALUE" -Model "TEST_VALUE" -Price "TEST_VALUE" -OldPrice "TEST_VALUE" -CostPrice "TEST_VALUE" -SpecialPrice "TEST_VALUE" -SpriceCreate "TEST_VALUE" -SpriceExpire "TEST_VALUE" -AdvancedPrices "TEST_VALUE" -MetaTitle "TEST_VALUE" -MetaDescription "TEST_VALUE" -MetaKeywords "TEST_VALUE" -CategoriesIds "TEST_VALUE" -StoresIds "TEST_VALUE" -Weight "TEST_VALUE" -Width "TEST_VALUE" -Height "TEST_VALUE" -Length "TEST_VALUE" -WeightUnit "TEST_VALUE" -WarehouseId "TEST_VALUE" -Quantity "TEST_VALUE" -ManageStock "TEST_VALUE" -InStock "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -TaxClassId "TEST_VALUE" -BackorderStatus "TEST_VALUE" -Status "TEST_VALUE" -Visible "TEST_VALUE" -IsVirtual "TEST_VALUE" -Downloadable "TEST_VALUE" -IsDefault "TEST_VALUE" -Upc "TEST_VALUE" -Isbn "TEST_VALUE" -Mpn "TEST_VALUE" -Ean "TEST_VALUE" -Barcode "TEST_VALUE" -AvailableForSale "TEST_VALUE" -IsFreeShipping "TEST_VALUE" -Taxable "TEST_VALUE" -SeoUrl "TEST_VALUE" -ManufacturerId "TEST_VALUE" -HarmonizedSystemCode "TEST_VALUE" -MarketplaceItemProperties "TEST_VALUE" -Images "TEST_VALUE" -ProductImagesIds "TEST_VALUE" -RelatedProductsIds "TEST_VALUE" -UpSellProductsIds "TEST_VALUE" -CrossSellProductsIds "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductVariantAddBatchPayloadInner
            #$NewObject.property | Should -Be 0
        }
    }
}
