#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAddBatchPayloadInnerAdvancedPricesInner' {
    Context 'ProductAddBatchPayloadInnerAdvancedPricesInner' {
        It 'Initialize-ProductAddBatchPayloadInnerAdvancedPricesInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAddBatchPayloadInnerAdvancedPricesInner -Value "TEST_VALUE" -GroupId "TEST_VALUE" -Quantity "TEST_VALUE" -StartTime "TEST_VALUE" -ExpireTime "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAddBatchPayloadInnerAdvancedPricesInner
            #$NewObject.property | Should -Be 0
        }
    }
}
