#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductVariantUpdateBatchPayloadInner' {
    Context 'ProductVariantUpdateBatchPayloadInner' {
        It 'Initialize-ProductVariantUpdateBatchPayloadInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductVariantUpdateBatchPayloadInner -Id "TEST_VALUE" -ProductId "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -ShortDescription "TEST_VALUE" -Sku "TEST_VALUE" -Upc "TEST_VALUE" -Mpn "TEST_VALUE" -Gtin "TEST_VALUE" -Isbn "TEST_VALUE" -Status "TEST_VALUE" -Price "TEST_VALUE" -SpecialPrice "TEST_VALUE" -CostPrice "TEST_VALUE" -RetailPrice "TEST_VALUE" -AdvancedPrices "TEST_VALUE" -Quantity "TEST_VALUE" -ReserveQuantity "TEST_VALUE" -IncreaseQuantity "TEST_VALUE" -ReduceQuantity "TEST_VALUE" -WarehouseId "TEST_VALUE" -ManufacturerId "TEST_VALUE" -Weight "TEST_VALUE" -Height "TEST_VALUE" -Length "TEST_VALUE" -Width "TEST_VALUE" -StoreId "TEST_VALUE" -LangId "TEST_VALUE" -TaxClassId "TEST_VALUE" -BackorderStatus "TEST_VALUE" -Visible "TEST_VALUE" -IsDefault "TEST_VALUE" -InStock "TEST_VALUE" -IsVirtual "TEST_VALUE" -Downloadable "TEST_VALUE" -ManageStock "TEST_VALUE" -IsFreeShipping "TEST_VALUE" -SeoUrl "TEST_VALUE" -MetaTitle "TEST_VALUE" -MetaDescription "TEST_VALUE" -MetaKeywords "TEST_VALUE" -CategoriesIds "TEST_VALUE" -StoresIds "TEST_VALUE" -Images "TEST_VALUE" -ProductImagesIds "TEST_VALUE" -RelatedProductsIds "TEST_VALUE" -UpSellProductsIds "TEST_VALUE" -CrossSellProductsIds "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductVariantUpdateBatchPayloadInner
            #$NewObject.property | Should -Be 0
        }
    }
}
