#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductTierPrice' {
    Context 'ProductTierPrice' {
        It 'Initialize-ProductTierPrice' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductTierPrice -Qty "TEST_VALUE" -Price "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductTierPrice
            #$NewObject.property | Should -Be 0
        }
    }
}
