#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductOptionAdd' {
    Context 'ProductOptionAdd' {
        It 'Initialize-ProductOptionAdd' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductOptionAdd -Name "TEST_VALUE" -Type "TEST_VALUE" -ProductId "TEST_VALUE" -DefaultOptionValue "TEST_VALUE" -OptionValues "TEST_VALUE" -Description "TEST_VALUE" -Avail "TEST_VALUE" -SortOrder "TEST_VALUE" -Required "TEST_VALUE" -Values "TEST_VALUE" -ClearCache "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductOptionAdd
            #$NewObject.property | Should -Be 0
        }
    }
}
