#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAddBatch' {
    Context 'ProductAddBatch' {
        It 'Initialize-ProductAddBatch' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAddBatch -NestedItemsUpdateBehaviour "TEST_VALUE" -ClearCache "TEST_VALUE" -Reindex "TEST_VALUE" -Payload "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAddBatch
            #$NewObject.property | Should -Be 0
        }
    }
}
