#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAddCertificationsInner' {
    Context 'ProductAddCertificationsInner' {
        It 'Initialize-ProductAddCertificationsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAddCertificationsInner -Id "TEST_VALUE" -Images "TEST_VALUE" -Files "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAddCertificationsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
