#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAttributeValueUnset200ResponseResult' {
    Context 'ProductAttributeValueUnset200ResponseResult' {
        It 'Initialize-ProductAttributeValueUnset200ResponseResult' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAttributeValueUnset200ResponseResult -Success "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAttributeValueUnset200ResponseResult
            #$NewObject.property | Should -Be 0
        }
    }
}
