#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductVariantAdd200Response' {
    Context 'ProductVariantAdd200Response' {
        It 'Initialize-ProductVariantAdd200Response' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductVariantAdd200Response -ReturnCode "TEST_VALUE" -ReturnMessage "TEST_VALUE" -Result "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductVariantAdd200Response
            #$NewObject.property | Should -Be 0
        }
    }
}
