#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ProductAttribute' {
    Context 'ProductAttribute' {
        It 'Initialize-ProductAttribute' {
            # a simple test to create an object
            #$NewObject = Initialize-ProductAttribute -AttributeId "TEST_VALUE" -Code "TEST_VALUE" -Name "TEST_VALUE" -LangId "TEST_VALUE" -StoreId "TEST_VALUE" -Value "TEST_VALUE" -Required "TEST_VALUE" -Visible "TEST_VALUE" -Type "TEST_VALUE" -Position "TEST_VALUE" -AttributeGroupId "TEST_VALUE" -ProductId "TEST_VALUE" -VariantId "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ProductAttribute
            #$NewObject.property | Should -Be 0
        }
    }
}
