#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ResponseCustomerListResult' {
    Context 'ResponseCustomerListResult' {
        It 'Initialize-ResponseCustomerListResult' {
            # a simple test to create an object
            #$NewObject = Initialize-ResponseCustomerListResult -CustomersCount "TEST_VALUE" -Customer "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ResponseCustomerListResult
            #$NewObject.property | Should -Be 0
        }
    }
}
