#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ResponseReturnListResult' {
    Context 'ResponseReturnListResult' {
        It 'Initialize-ResponseReturnListResult' {
            # a simple test to create an object
            #$NewObject = Initialize-ResponseReturnListResult -TotalCount "TEST_VALUE" -Returns "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ResponseReturnListResult
            #$NewObject.property | Should -Be 0
        }
    }
}
