#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TaxClassZipCodesRange' {
    Context 'TaxClassZipCodesRange' {
        It 'Initialize-TaxClassZipCodesRange' {
            # a simple test to create an object
            #$NewObject = Initialize-TaxClassZipCodesRange -VarFrom "TEST_VALUE" -To "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType TaxClassZipCodesRange
            #$NewObject.property | Should -Be 0
        }
    }
}
