#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TaxClassCountries' {
    Context 'TaxClassCountries' {
        It 'Initialize-TaxClassCountries' {
            # a simple test to create an object
            #$NewObject = Initialize-TaxClassCountries -Id "TEST_VALUE" -Name "TEST_VALUE" -Code "TEST_VALUE" -Tax "TEST_VALUE" -TaxType "TEST_VALUE" -States "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType TaxClassCountries
            #$NewObject.property | Should -Be 0
        }
    }
}
