#
# API2Cart OpenAPI
# API2Cart
# Version: 1.1
# Contact: contact@api2cart.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TaxClass' {
    Context 'TaxClass' {
        It 'Initialize-TaxClass' {
            # a simple test to create an object
            #$NewObject = Initialize-TaxClass -Id "TEST_VALUE" -Name "TEST_VALUE" -Avail "TEST_VALUE" -Tax "TEST_VALUE" -TaxType "TEST_VALUE" -CreatedAt "TEST_VALUE" -ModifiedAt "TEST_VALUE" -AdditionalFields "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType TaxClass
            #$NewObject.property | Should -Be 0
        }
    }
}
